### ISSUE TITLE
Shadow Flyout

### ISSUE THREAD

**Issue by almas3s** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1007]
hi. how i can set Shadow for Flyout ??
[like this:](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/tree/master/MahMaterialDragablzMashUp)

![14245345](https://user-images.githubusercontent.com/40490538/44005642-cc6cce66-9e8b-11e8-9bb4-3a0265c386b5.PNG)

I copy and paste all this code in my program but Flyout There is no shadow

**Comment by Keboo** [comment]
@almas3s Probably need to see your code to be sure, but it sounds like it is not able to find the MDIX shadow resource.

Have you made sure to also reference the [MaterialDesignThemes.MahApps nuget package](https://www.nuget.org/packages/MaterialDesignThemes.MahApps/)? This package provides the material design theme for the MahApps flyout.

Does your App.xaml match what is [in the example](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MahMaterialDragablzMashUp/App.xaml)? These resources are needed so that the material design theme for the flyout can properly find the shadow.

**Comment by Keboo** [comment]
Closing for now due to inactivity. If there is still an issue please re-open with details.
