### ISSUE TITLE
MahApps Flyout - Error locating resource pack

### ISSUE THREAD

**Issue by svjansen** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1012]
I was just looking into MahApps in combination with materialdesign and worked down the guide. 
However I can't get it running it. I've just copied the App.xaml [from guide](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/MahApps.Metro-integration#the-appxaml) and got an error on `<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.MahApps;component/Themes/MaterialDesignTheme.MahApps.Flyout.xaml" />`  the `<ResourceDictionary><ResourceDictionary.MergedDictionaries>` is there of course just hidden behind the tooltip.
![resourcerror](https://user-images.githubusercontent.com/4349103/44079212-c31afbbc-9fa8-11e8-808f-ce6d97e9309f.png) 

> Error locating resource pack://application:,,,/MaterialDesignThemes.MahApps;Component/Themes/MaterialDesignTheme.MahApps.Flyout.xaml (google translator :D)

I got the following packages installed

![packages](https://user-images.githubusercontent.com/4349103/44079323-06c65e56-9fa9-11e8-90f3-b221a741db24.png)

Anything I'm missing here?

**Comment by jiewei915** [comment]
yes,the same problem. 
I compare with the example,only difference is the version of MaterialDesignTheme.MahApps.dll.
Maybe in the new version,there is no need to import the Flyout.xaml dictionary.

**Comment by Keboo** [comment]
I suspect the issue here is a mismatch in versions.
The MaterialDesignThemes.MahApps nuget is expecting to target MahApps 1.2.* (though the nuget doesn't restrict it to that version). 
There are known issues with the latest MahApps nuget (1.6.*). These have been addressed on the master branch and will be released as part of the 2.5.0 (upcoming) release; however there are not any nuget packages that have been released for this yet.
The guide that you referenced above is out dated and will need to be updated for the latest 2.5.0 work that is coming.

So a few possible solutions (though none are ideal atm)
1. Downgrade your MahApps.Metro to 1.2.*
2. Compile the latest MaterialDesignThemes.MahApps project from the master branch and manually reference it.

**Comment by svjansen** [comment]
I've found an Issue here where somebody suggested the [MahApps.163 nuget](https://www.nuget.org/packages/MaterialDesignThemes.MahApps.163/) which fixed my problem for now.
However thanks for the answer.

My current nuget setup look like the following which is working without any problem.

![new_nuget](https://user-images.githubusercontent.com/4349103/44445555-ac324380-a5e1-11e8-9fa8-7c7287ae66a2.png)

**Comment by Keboo** [comment]
This should be fixed with the latest 2.5.0 release. Let me know if there are still issues.
