### ISSUE TITLE
DataGrid MaterialDataGridTextColumn bug or feature

### ISSUE THREAD

**Issue by DK-93** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1055]
Hello,

I'm not sure that it is a bug or the desired behavior, but it could be annoying and it is present in the demo application. If you are using the `Datagrid` control with `MaterialDataGridTextColumn` column with `MaterialDesignDataGridTextColumnPopupEditingStyle` style and select the cell and press a key the popup will open correctly, but the pressed key will not show in the TextBox inside the popup. So every time, if you want to set a new value you have to press the first character twice, because the first attempt will just open the popup. An easy fix could be to add the `base.PrepareCellForEdit(editingElement, editingEventArgs);` row in the `PrepareCellForEdit `override implementation.

Regards, David

**Comment by TysonMN** [comment]
I just tried and failed to reproduce the behavior you describe.  Maybe this issue was fixed.  @DK-93, can you test again on the head of `master`?

I tested using the `MaterialDesignDemo` project.  On the `Data Grids` screen and under `Custom Columns`, the column with header `Name` is using `MaterialDesignDataGridTextColumnPopupEditingStyle`.  When interacting with the column, I didn't experience any bad behavior.

![2020-12-22_07-53-25_440_MaterialDesignDemo](https://user-images.githubusercontent.com/34664007/102895842-131ecc00-442b-11eb-986d-1bfa30f128ed.png)

https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/c36307b01f5a47f0b9cf1ede8adb4d7ca5546a34/MainDemo.Wpf/DataGrids.xaml#L65-L77

**Comment by zqfname** [comment]
![image](https://user-images.githubusercontent.com/93236995/139831788-efa28ecc-4dad-463d-be62-3279f3c0f96a.png)
click bor
![image](https://user-images.githubusercontent.com/93236995/139832400-5e27f4e0-500c-4a78-9a8e-bd08f46e616b.png)
I have also encountered this problem. Unfortunately, I need to click on the border of the content, and there is no response to clicking on the content, and most people will not operate it. This makes me very distressed.
