### ISSUE TITLE
The mouse is active before coming on the button. Is this correctable?

### ISSUE THREAD

**Issue by mummyildiz** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1079]
![button](https://user-images.githubusercontent.com/5136066/47257982-a94ab680-d49d-11e8-8ef2-d7c70acafc89.gif)

The mouse is active before coming on the button. Is this correctable?

**Comment by Keboo** [comment]
@mummyildiz yes this is expected behavior. The PopupBox control has a [PopupMode property that defaults to MouseOverEager](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PopupBox.xaml#L155). You can change it to `MouseOver` or `Click` to get alternate behavior.
