### ISSUE TITLE
Dialog Inside Dialog Does not work. Multiple Issue Please read

### ISSUE THREAD

**Issue by infirazor** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1120]
Hello Everyone,

Please read below issues which i am facing while working, with multiple dialogs and user control.

Issue : 1) Dialog Inside Another Dialog is not working.
	1.1)It works if we run CustomerView as startup and then click on Add New Customer from pop up menu.
	->I've a Add New Customer User Control to add new customer.
Issue : 2) Not able to open Window as Dialog using given code in MD:Issue https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/1085

	Manager.ShowDialog works but does not resolve my proble.( Issue : 1)
	Manager.ShowPopup does not work.
	Manager.ShowWindow works but does not resolve my proble.( Issue : 1)

Issue :3) Dont know how to close UserControl and Window using button that is inside them.
	-> UserControl Does have Close button but dont know how to close it when it is showing inside DialogHost other then ClickOnAway.
	-> Window Does have Close button but dont know how to close it when it when it is showing ShowDialog.
		I tried : (GetView() as Window).Close(); but it gives error so I've commented it.

Please suggest a recommended way to Open and Close Windows and User Controls in WPF with MVVM.

=> Windows Name and Type :

ShellView(ShellViewModel) - Window
CustomersView(CustomersViewModel) - Window
AddNewCustomerView(AddNewCustomerViewModel) - UserControl

Frameworks used:
Caliburn.Micro
MaterialDesignInXAML

I've created a sample repo to show issue : Please ignore my silly mistakes, I am new to wpf mvvm world.
https://github.com/infirazor/DialogIssue

**Comment by infirazor** [comment]
Hello @Keboo can you please help on this, its been 10 days and I am getting nothing out of this.

**Comment by Keboo** [comment]
@infirazor there are several things going on here. 
First, I am not much of a caliburn expert since I don't like using it.

1.
When you use `DialogHost.Show` it has to try and determine which DialogHost to use to show your dialog. The issue you are running into is that when you open the second window there are now **two** instances of the dialog host. One in your `ShellView` and one in your `CustomersView`. In this case the DialogHost.Show method can't figure out which one to use so it throws an exception with the message: "Multiple viable DialogHosts.  Specify a unique Identifier on each DialogHost, especially where multiple Windows are a concern." This is where caliburn is un-helpfully swallowing the exception and not showing it to you. If you wrap your `DialogHost.Show` method in a `try/catch` block you can see the exception.

When you have more than one instance of the DialogHost, you need to specify the `Identifier` property on the DialogHost (which it looks like you did). And you have to pass this same identifier to the `DialogHost.Show` method. 
So inside of `CustomerViewModel.AddNewCustomer` your method call should look like this:
```C#
await DialogHost.Show(uiElement, "RootDialog1");
```
If you are designing an app that will have multiple DialogHost instances I recommend always passing the the identifier.

2. 
In WPF it is not possible to use a Window control within any other control. It always has to be a top level control. For this library it means that you cannot use it as a dialog since the dialogs are put inside of a popup. A better design is to create your dialog content as a UserControl rather than as a Window. If it needs to remain as a Window you could change ShellViewModel.OpenWindow like this:

```C#
var viewModel = new CustomersViewModel();
Window window = (Window)ViewLocator.LocateForModel(viewModel, null, null);
ViewModelBinder.Bind(viewModel, (DependencyObject)window.Content, null);
await DialogHost.Show(window.Content, "RootDialog");
```

3. 
There are several ways to handle closing a dialog. If you are working with WPF control that is inside of the dialog and simply want to close with (without any special code), you can use the static relay command. 
Using you `CustomersView.xaml` as an example you would do it like this:
```XAML
<UserControl
    x:Class="DialogIssue.Views.AddNewCustomerView"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local="clr-namespace:DialogIssue.Views"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
    Width="480"
    Height="380"
    Background="White"
    mc:Ignorable="d">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition />
            <RowDefinition />
            <RowDefinition />
        </Grid.RowDefinitions>
        <TextBlock
            Grid.Row="0"
            HorizontalAlignment="Center"
            VerticalAlignment="Center"
            Text="Wow ! Dialog Opened" />
        <TextBlock
            Grid.Row="1"
            HorizontalAlignment="Center"
            VerticalAlignment="Center"
            Text="But dont know how to close this :(" />
        <Button Grid.Row="2" Content="Close" Command="{x:Static materialDesign:DialogHost.CloseDialogCommand}" />
    </Grid>
</UserControl>
```

Now if want to do it programmatically from the view model you will need to use the dialog session. This gets a little more complicated. So using `ShellViewModel.OpenWindow` as an example again. You start by adding a callback that is invoked when the dialog is shown. Like this:
```C#
var viewModel = new CustomersViewModel();
Window window = (Window)ViewLocator.LocateForModel(viewModel, null, null);
ViewModelBinder.Bind(viewModel, (DependencyObject)window.Content, null);
await DialogHost.Show(window.Content, "RootDialog", new DialogOpenedEventHandler((sender, args) =>
{
    viewModel.WithDialogSession(args.Session);
}));
```
Then make some changes in `CustomersViewModel` like this:
```C#
public void Exit()
{
    //Any logic you want to determine if the close should happen
    _DialogSession.Close();
}

private DialogSession _DialogSession;
public void WithDialogSession(DialogSession session)
{
    _DialogSession = session;
}
```

If you want more information on the various opening and closing options for the DialogHost, take a look at the [wiki](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Dialogs) and [this blog post](https://intellitect.com/material-design-in-xaml-dialog-host/).

**Comment by infirazor** [comment]
Thank you @Keboo 
That was all I needed,
After all I am doubting on my self for using Caliburn.Micro, things are getting messy with this now.
Anyways...Thank you.
