### ISSUE TITLE
Add Support For .NET Core 3.0

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1134]
WPF will support .NET Core 3.0.

This is a parent issue for any compatibility issues that are raised.
https://blogs.msdn.microsoft.com/dotnet/2018/12/04/announcing-net-core-3-preview-1-and-open-sourcing-windows-desktop-frameworks/

**Comment by enizvk** [comment]
Any news or plans on this?

**Comment by StevenHanquez** [comment]
Same question. Any news about support for .NET Core 3.0 ?

**Comment by jespersh** [comment]
Hi,

The only issue I currently have with porting this to netcoreapp3.0 is ShowMeTheXaml.
My last commit here https://github.com/jespersh/MaterialDesignInXamlToolkit removed all the ShowMeTheXaml (last elegantly, so all controls in a grid is a mess currently) for a quick revert once SMTX works.
So while it is entirely possible... The change most endangering is that this might not make .Net framework work (unless maybe 4.7.2)

![image](https://user-images.githubusercontent.com/1004198/61207588-c000ff80-a6f5-11e9-9f9d-da998e5e3710.png)

![image](https://user-images.githubusercontent.com/1004198/61207730-1ff7a600-a6f6-11e9-9d81-854a2b961dff.png)

**Comment by Keboo** [comment]
@jespersh that is great. If you want to get a PR open we can start looking at getting it merged. I have a preview NuGet for ShowMeTheXaml that is out that adds .Net Core 3.0 support as well.

**Comment by enizvk** [comment]
Awesome, Thanks! I just migrated my project to Core 3 and everything seems alright so far.

**Comment by dansef** [comment]
Got error

C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(3056,5): error MSB4216: Could not run the "GenerateResource" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x86".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\MSBuild.exe" exists and can be run. [C:\Users\User\source\repos\MaterialDesignInXamlToolkit\MainDemo.Wpf\MaterialDesignDemo.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(3056,5): error MSB4216: Could not run the "GenerateResource" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x86".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\MSBuild.exe" exists and can be run. [C:\Users\User\source\repos\MaterialDesignInXamlToolkit\MahMaterialDragablzMashUp\MahAppsDragablzDemo.csproj]
    18 Warning(s)
    2 Error(s)

**Comment by dansef** [comment]
For UWP:

C:\Users\User\source\repos\MaterialDesignInXamlToolkit\MaterialDesignThemes.Uwp\MaterialDesignThemes.Uwp.csproj(237,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\Microsoft\WindowsXaml\v16.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\Users\User\source\repos\MaterialDesignInXamlToolkit\MainDemo.Uwp\MainDemo.Uwp.csproj(142,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\Microsoft\WindowsXaml\v16.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
    3 Warning(s)
    2 Error(s)

**Comment by jespersh** [comment]
@dansef what commands are you building with?

**Comment by Keboo** [comment]
Closing as the work for this has been done. For those wishing to try this out there are a few things to know.
1. This is only available with the 3.0.0 _**preview**_ NuGet packages
2. MahApps is not currently supported with .NET Core 3.0, only the MaterialDesignThemes and MaterialDesignColors NuGet packages are expected to work. MahApps support will be forthcoming.
