### ISSUE TITLE
Bad TextBox Scrollbar Hover Color with Black Background

### ISSUE THREAD

**Issue by M0n7y5** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1145]
Hello, 
I have a small problem ... I have TextBox with Scrollbar enabled. When TextBox background color is changed to Black, then hover color effect of the Scrollbar is also black so you can't see it.
Example:
![hilx06ddaa](https://user-images.githubusercontent.com/17201053/49944055-c625c800-fee9-11e8-8236-3b56836bd9ce.gif)

XAML code:
```XAML
<TextBox VerticalScrollBarVisibility="Auto"  Padding="2" 
                         Background="Black" Foreground="LimeGreen"
                         AcceptsReturn="True"/>
```
Additional Info:
WPF
.Net Framework **4.7.2**
MaterialDesignThemes **2.5.0**

**Comment by Keboo** [comment]
Hi @M0n7y5 
I suspect you are using the light theme in your application, which is the reason for the black color that you are seeing. The ScrollBar's brush is controlled by [a trigger](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ScrollBar.xaml#L20-L23) that sets it to use the `MaterialDesignDivider` theme brush. This brush has a [black color in the light theme](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/b0092634ebc36a76e382fc619726bf185e83c675/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Dark.xaml#L20) and a [gray-ish color in the dark theme](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/b0092634ebc36a76e382fc619726bf185e83c675/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Dark.xaml#L20). 

So for your use-case you have a couple options:
1. Use the Dark theme instead of the light theme. If applicable you could do this for your entire application. Alternatively if you just want it for the text box you could set it with the `ThemeAssist.Theme` property directly on the TextBox. 
2. Simply provide an alternate resource for the `MaterialDesignDivider` theme brush. This is as simple as putting a brush in the TextBox's resources that has the same key.
```XAML
<TextBox.Resources>
    <SolidColorBrush x:Key="MaterialDesignDivider" Color="Fuchsia" />
</TextBox.Resources>
```

**Comment by M0n7y5** [comment]
Ok ... I used the second solution and it works perfectly. Thanks!
