### ISSUE TITLE
New look of outlined text field

### ISSUE THREAD

**Issue by lszczygielek** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1188]
Hi,
I'm submitting this feature request after discussion with Kevin B-Keboo on the Gitter.

There is a outlined text field on [material.io](https://material.io/design/components/text-fields.html#usage). Here is a screenshot:
![image](https://user-images.githubusercontent.com/41156511/52540839-89156f00-2d8e-11e9-8a9a-0d4ad292a032.png)

It would be nice to add such look and feel and also with support for floating hint which moves to border.

Best regards,
Łukasz

**Comment by AlbertAlonso** [comment]
Would it be okay to try to create a new style with a key for a SmartHint, but instead of `ContentControl.LayoutTransofrm`, wrap the `ControlControl` _FloatingHintTextBlock_ with a Border where we apply the transformation? 

This would allow us to add a Background to the Hint. The position of the floating hint can be modified in this style so it doesn't affect the other ones. And create a `Trigger` in the TextBox Template to change the style to this one when `OutlinedTextFieldTextBox = True`. 

The modifications to the `TextBox` `Template` must take into consideration:
- The Hint `Foreground` must match the borderbrush when keyboard is focused. 
- The Margin must be set to `Margin = "0,-16"` so that the hint is in the middle of the border.
- When the `TextBox` is not focused and the `Text` is filled, the color is more dark than the usual one. 
- The Padding must change so that the text doesn't fell so away of the borders. 

If this approch seems good enough I could make a pull request.  However, it presents at least one issue. 
- The background of the Hint has to be the same as the background behind the textblock, which I don't know how to indicate. 

Nevertheless, the test I've made seems to be a good WIP. 
I am not sure I have explain myself quite cleary, but before pulling a request, I wanted to discuss it.

**What do you think?**

![1188_Enabled](https://user-images.githubusercontent.com/38870744/55655046-579bab80-57f3-11e9-8af9-d42e48ecce41.png)
![1188_Unfocused](https://user-images.githubusercontent.com/38870744/55655047-579bab80-57f3-11e9-8bd3-44613e0b528d.png)

**Comment by Keboo** [comment]
@AlbertAlonso I the look of what you have produced. I do think we could probably avoid some of the issues you mentioned by using multiple Border controls. The [default WPF GroupBox template](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/groupbox-styles-and-templates) has a very similar layout where it puts the header content right in the middle of the border. I think we could do something similar here. This should avoid the need of having to set the background on the Hint, since the border would have a "hole" inside of it. Thoughts?

**Comment by Keboo** [comment]
This is now working in the latest 3.1.1 release
