### ISSUE TITLE
ComboBox can't contain images

### ISSUE THREAD

**Issue by xthehacker2000x** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1203]
```
<ComboBox>
     <ComboBoxItem >
         <Image Source="/Resources/red.png" />
     </ComboBoxItem>
</ComboBox>
```

the image is shown in the drop-down menu but not when the item with an image is selected

**Comment by dyno0919** [comment]
If this helps anyone, I was able to fix this by modifying MaterialDesignComboBoxItemTemplate and simply adding a RowDefinition to GridWrapper with Height="Auto".

i.e.:
```
<ControlTemplate x:Key="MaterialDesignComboBoxItemTemplate" TargetType="{x:Type ComboBoxItem}">
    <Grid x:Name="GridWrapper">
        <Grid.RowDefinitions>
            <RowDefinition Height="auto"/>
        </Grid.RowDefinitions>
...

**Comment by kramolisdavid** [comment]
> 
> 
> If this helps anyone, I was able to fix this by modifying MaterialDesignComboBoxItemTemplate and simply adding a RowDefinition to GridWrapper with Height="Auto".
> 
> i.e.:
> 
> ```
> <ControlTemplate x:Key="MaterialDesignComboBoxItemTemplate" TargetType="{x:Type ComboBoxItem}">
>     <Grid x:Name="GridWrapper">
>         <Grid.RowDefinitions>
>             <RowDefinition Height="auto"/>
>         </Grid.RowDefinitions>
> ...
> ```

I was also affected by this issue and this really solves it, the bug is also related to [#601](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/601) and [#1513](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/1513), which is also solved by this fix. So far what I can tell (tested it using redefined template), it properly visualise static comboboxes, where selection was broken, (comboboxes defined only using ComboBoxItem, ItemsSource is not programatically or binding given) - it now again works with single image, with single textblock, with stackpanel (combination of image plus textblock) and already properly working comboboxes with programatically or binding defined ItemsSource are still valid.
