### ISSUE TITLE
DialogHost Alignment

### ISSUE THREAD

**Issue by NTesla1943** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1230]
How can I alignment dialoghost content to bottom? Default it always start center (vertical and horizontal), not matter what I specific in dialoghost properties.

**Comment by jespersh** [comment]
I don't think you can, since PopupEx in DialogHost doesn't expose `PlacementMode`
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/e4b59d4b61fed5421ee548966b16caa9ed8b3ffe/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DialogHost.xaml#L159-L162

PlacementModes:
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/2a978a80737e99b8bb2069fb791c828afdf8837f/MaterialDesignThemes.Wpf/PopupBox.cs#L19


You could copy the entire style and create your own.

**Comment by Keboo** [comment]
@NTesla1943 this is certainly possible though not very straight forward. The DialogHost does expose the Style for the popup which gives you a way to set properties and modify the popup itself. The only thing to note is the placement of dialogs is a little special since the DialogHost tried to use those properties when showing the dialog. What you can do is manipulate the VertialOffset of the popup to push it down and effectively anchor it to the bottom.

You can see an example of doing this [here](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/DialogHost/DialogHost.AnchorBottom)

**Comment by Wrozebnik** [comment]
@Keboo do You have any idea how can I make DialogHost dragable like Window? I try with Thumb bases on this example [Drag WPF Popup](https://stackoverflow.com/a/8170666), but this work unexpected - alignment to screen corners. Below my changes in DialogHost.cs

        public override void OnApplyTemplate()
        {
            if (_contentCoverGrid != null)
                _contentCoverGrid.MouseLeftButtonUp -= ContentCoverGridOnMouseLeftButtonUp;

            _popup = GetTemplateChild(PopupPartName) as Popup;
            _popupContentControl = GetTemplateChild(PopupContentPartName) as ContentControl;
            _contentCoverGrid = GetTemplateChild(ContentCoverGridName) as Grid;

            if (_contentCoverGrid != null)
                _contentCoverGrid.MouseLeftButtonUp += ContentCoverGridOnMouseLeftButtonUp;

            Grid grid = GetTemplateChild("DialogHostRoot") as Grid;

            var thumb = new Thumb {
                Width = 0,
                Height = 0,
            };
            grid.Children.Add(thumb);

            MouseDown += (sender, e) =>
            {
                thumb.RaiseEvent(e);
            };

            thumb.DragDelta += (sender, e) =>
            {
                _popup.HorizontalOffset += e.HorizontalChange;
                _popup.VerticalOffset += e.VerticalChange;
            };

            VisualStateManager.GoToState(this, SelectState(), false);

            base.OnApplyTemplate();
        }
`

**Comment by Keboo** [comment]
@Wrozebnik see #1196, it is not currently possible.

**Comment by Keboo** [comment]
Closing for now as it appears the question has been answered.
