### ISSUE TITLE
PopupBox and DataTemplate (MVVM)

### ISSUE THREAD

**Issue by Wrozebnik** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1234]
How can I set DateTemplate in PopupBox? I tried few methods but all of them don't work - view doesn't show itself.

**Comment by Wrozebnik** [comment]
Solution:
0. Base files
```
MainWindow - view with Popup
MainViewModel - viewmodel for MainWindow
PopupView - view displayed in Popup
PopupViewModel - viemodel for PopupView
```

1. Create ResourceDictionary file (PopupData.xaml)
```
<ResourceDictionary ... (namespace etc)
    <DataTemplate DataType = { x:Type PopupViewModel }”
        <PopupView>
    </DataTemplate>
</ResourceDictionary>
```

2. Add ResourceDictionary file to App.xaml as MergedDictionaries
```
<Application ... (namespace etc)
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="...PopupData.xaml"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

3. Add in MainViewModel property for PopupViewModel 
```
private PopupViewModel _popupViewModel;
public PopupViewModel PopupViewModel
{
    get { return _popupViewModel; }
    set
    {
        _popupViewModel = value;
        OnPropertyChanged("PopupViewModel");
    }
}
```

4. Add RelayCommand in MainViewModel to set property from step 3 when Popup click/Popup open
```
a) property: 
public RelayCommand CreatePopupCommand { get; private set; }
b) constructor: 
CreatePopupCommand = new RelayCommand(CreatePopup);
c) method:
public void CreatePopup()
{
    PopupViewModel = new PopupViewModel();
}
```


5. Modify Popup in MainWindow
a) Add RelayCommand to ToggleCheckedContentCommand - CreatePopupCommand
b) Set PopupContent - property PopupViewModel in MainViewModel
```
<materialDesign:PopupBox ToggleCheckedContentCommand="{Binding CreatePopupCommand}">
    <materialDesign:PopupBox.PopupContent>
        <ContentControl Content={Binding PopupViewModel, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
    </materialDesign:PopupBox.PopupContent>
</materialDesign:PopupBox>
```

6. Add code to PopupBox.cs OnOpened method
```
if (ToggleCheckedContentCommand != null && ToggleCheckedContentCommand.CanExecute(ToggleCheckedContentCommandParameter))
{
    ToggleCheckedContentCommand.Execute(ToggleCheckedContentCommandParameter);
}
```

**Comment by Keboo** [comment]
@Wrozebnik take a look at [this example](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/PopupBox/PopupBox.PopupContentTemplate).

When using a PopupBox the data _inside_ of the `PopupContent` will be displayed inside of a popup. This effectively puts it inside of its own window so it wont be able to resolve resources from the main window. You can work around this by either 1) putting the needed resources in App.xaml (or referenced by App.xaml) or 2) using the `PopupContentTemplate` (like what is done in the linked example), so that it can resolve items. Let me know if you have any more questions.
