### ISSUE TITLE
Exception closing DialogHost with CloseOnClickAway enabled

### ISSUE THREAD

**Issue by DenZuck** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1271]
I have defined my DialogHost in MainWindow.xaml
```javascript
    <materialDesign:DialogHost Identifier="RootDialog" CloseOnClickAway="True">
        <Grid>
            <Button Content="Dialog" Click="OnDialogClick"/>
        </Grid>
    </materialDesign:DialogHost>
```

and open a UserControl with
```javascript
            var dialog = new MyDialog();
            bool ret = (bool)await DialogHost.Show(dialog, "RootDialog");
```

when I click on overlay area I get the exception "Reference to an object not set in an instance object".

<img width="938" alt="image" src="https://user-images.githubusercontent.com/7376037/58976683-5a515780-87c8-11e9-999a-99aa04d9fdba.png">

The weird thing is that without ret value I don't get the error
```javascript
            var dialog = new MyDialog();
            await DialogHost.Show(dialog, "RootDialog");
```

MaterialDesignTheme version is 2.5.1

What am I missing ?

This is a project to reproduce the problem.

[TestDialog.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/3258323/TestDialog.zip)

**Comment by DenZuck** [comment]
I've discovered on my own that the problem was in ret value. The right way to handle the ret value is:

```javascript
            var dialog = new MyDialog();
            bool? ret = await DialogHost.Show(dialog, "RootDialog") as bool?;
```

**Comment by Keboo** [comment]
Hi @DenZuck First, thank you for the well written bug report! 
I see you found a solution, but I wanted to give a little more context for anyone else who may hit this.
The DialogHost has `CloseOnClickAwayParameter` that you can set, to allow you to return a specified value when the dialog is closed by clicking the darkened overlay. This defaults to `null` if not set. 
Because the type of this property is `object` if you want to set it in XAML and return a `bool` you will need to use element syntax like this:
```XAML
<materialDesign:DialogHost.CloseOnClickAwayParameter>
    <system:Boolean>False</system:Boolean>
</materialDesign:DialogHost.CloseOnClickAwayParameter>
```

As for the `NullReferenceException`, this is a bit of an un-usual case in C#. 
You will note that this code is functionally equivalent and also cases the `NullReferenceException`.
```cs
bool foo = (bool)(object)null;
```
In this case we have a null object reference that is being [unboxed](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/boxing-and-unboxing) into a boolean.
If you look at the IL that the compiler emits for this you will get:
```
    IL_000f: ldnull
    IL_0010: unbox.any    [mscorlib]System.Boolean
    IL_0015: stloc.0      // foo
```
The key here is that `unbox.any` instruction. If we look at the [docs for unbox.any](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.unbox_any) you will notice that it will throw a `NullReferenceException` if the reference on the stack is `null`. Which is the exception you were seeing.
