### ISSUE TITLE
How set placeholder in textbox?

### ISSUE THREAD

**Issue by SKProCH** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1274]
We can set a hint for TextBox, which will also be in the role of its title. 
However, I would like to make it so that the prompt would always be the title (and not only when there is something in TextBox), and there was a placeholder, as in html. Like [this](https://material.io/design/components/text-fields.html#usage) -
![image](https://user-images.githubusercontent.com/29896317/59081363-5ae80c00-88f6-11e9-986d-bcfda5c8f13c.png)
How can I do it?

**Comment by AlbertAlonso** [comment]
Currently there is no watermark feature, but maybe it is worth considering it.
 
What I propose is:
1. Create a TextFieldAssist.Watermark property, so it is easy to set.
2. Maybe create a Watermark control (equivalent to SmartHint?) to control brushes and behavior.
2. Adjust TextBlock style so that when the watermark is not empty, the label is floating and add the Watermark control. 

and that should do it, I guess? Let me know what you think.

**Comment by SKProCH** [comment]
Sorry, I forgot about this issue. And about the implementation - I probably won’t tell you, because I’m not very good at WPF.

**Comment by gigios** [comment]
I know that this is an old issue (if necessary I can open new one)
I'm trying to use for the first time the MaterialDesignToolkit, I have my application that use the MahApps.Metro and I'm able to the MaterialDesignToolkit.MahApps integration.

Now I need to show a watermark text over the Textbox. Without the MaterialDesignToolkit all works fine, with the MaterialDesignToolkit the TextBox is empty without any watermark text.
I have checked also the suggested helper class (TextFieldAssist) but there isn't a property Watermark.

Ho I can show a text in a similar way shown in the pictures in the first topic?
