### ISSUE TITLE
Please, expose corner raduis property for Badge

### ISSUE THREAD

**Issue by HuggerCoursera** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1279]
I'd like to ask for Badge corner radius property exposure. As far as I understand, for now badge corner radius can be modified only by providing custom content control style. It would be handy if that property could be set directly on control declaration in XAML.

**Comment by Keboo** [comment]
For anyone who would like to pick this one up:

- The change should be done in `Badged` not `BadgedEx` (this class lives in the [ControlzEx](https://github.com/ControlzEx/ControlzEx) repo)
- The issue is that right now we hard code the corner radius on the Border control inside of the [badge template](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Badged.xaml)
- Add a new CornerRadius dependency property. It should be of type `System.Windows.CornerRadius`
- In the default style for Badged, add a Setter to default the value of this new property to 9 to match what it is now.
- In the Badged control template use the new dependency property rather than the hard coded value of 9.
