### ISSUE TITLE
In PopupBox.xaml , is there a way to have the three dots horizontal rather than vertical?

### ISSUE THREAD

**Issue by SachinGoyalSAP** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1287]
In PopupBox.xaml , is there a way to have the three dots horizontal rather than vertical?

**Comment by AlbertAlonso** [comment]
For now you have to make the change manually
```
<materialDesign:PopupBox>
    <materialDesign:PopupBox.ToggleContent>
        <materialDesign:PackIcon Kind="DotsHorizontal" />
    </materialDesign:PopupBox.ToggleContent>                                       
</materialDesign:PopupBox>
```
If you are asking how to add an built in method, maybe a Property `DotsOrientation` using the [Orientation Enum](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.orientation?view=netframework-4.8), and adding a Trigger in MaterialDesignPopupBox in PopupBox.xaml?

 I have done the change many times because it is true that some situations the dots look better used horizontaly.

**Comment by Keboo** [comment]
@AlbertAlonso answer is correct. I have also added this information to the [wiki](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/PopupBox).

If this does not resolve your issue please re-open.
