### ISSUE TITLE
IconPack resize in button

### ISSUE THREAD

**Issue by raimand13** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1326]
Hi, i use this code in xaml :
![image](https://user-images.githubusercontent.com/14857040/61471028-4d16b380-a997-11e9-9ae3-1231a0ad539e.png)

Icon will not resize when i maximize the window.
Screenshot :
![image](https://user-images.githubusercontent.com/14857040/61470478-6cf9a780-a996-11e9-9e52-28fc1919f2aa.png)
Thank you.

**Comment by Mrxx99** [comment]
I think you have to put the icon into a ViewBox for resizing

**Comment by raimand13** [comment]
I try ViewBox and also ContentPresenter.
icons can resizing well when i set `WindowState="Maximized"` but icons can not resize on `WindowState="Normal"` and user maximize the window.

**Comment by Keboo** [comment]
The issue here is with the Clip property that is being applied to the ripple control. We put in the Clip to handle the case of the ripple animation extending outside of the raise button when it has a corner radius set. See #1288 for details. 
It appears with this setup the clip is not sufficient and caused the content to be clipped. Setting an explicit Width/Height on the `PackIcon` does address it.

**Comment by Keboo** [comment]
This appears fixed on the latest 3.0.0 code. Commit: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/commit/7cd142e501dde316fe2cf9ab3352ecb9036cc220
