### ISSUE TITLE
MaterialDesignDemo Violating MVVM DialogsViewModel

### ISSUE THREAD

**Issue by Quadrition** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1337]
I'm not a professional in MVVM pattern, I just want to ask isn't creating an instance of the view called SampleDialog in the DialogsViewModel (line 50) breaking an MVVM pattern, because you are creating an instance of a view in the viewmodel? There is also a comment line above it saying "let's set up a little MVVM"?

**Comment by MichelMichels** [comment]
In theory, this is a violation of the separation of View and ViewModel, but in practice, it's sometimes easier to cheat a little on the pattern. But yes, you are correct in your assessment.

**Comment by Keboo** [comment]
Yes absolutely this is a violation of the separation of concerns in the MVVM pattern. The demo app in this library is setup to show the breadth of what is possible, so it shows both MVVM and non-MVVM examples, and in many cases directly violates the MVVM pattern. 

I have [several DialogHost examples](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/DialogHost) you can take a look at, but specifically the [FromViewModel](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/DialogHost/DialogHost.FromViewModel) one shows a better solution since it only has one ViewModel creating another ViewModel. It is worth pointing out that there is still strong coupling between the ViewModel and the DialogHost control itself. Typically I would abstract this away behind an interface for unit testing.
