### ISSUE TITLE
Additional PopupBox PlacementMode options

### ISSUE THREAD

**Issue by Anopob** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1387]
Currently, the PopupBox control has 12 placement modes:

        BottomAndAlignLeftEdges
        BottomAndAlignRightEdges,
        BottomAndAlignCentres,
        TopAndAlignLeftEdges,
        TopAndAlignRightEdges,
        TopAndAlignCentres,
        LeftAndAlignTopEdges,
        LeftAndAlignBottomEdges,
        LeftAndAlignMiddles,
        RightAndAlignTopEdges,
        RightAndAlignBottomEdges,
        RightAndAlignMiddles,

I was hoping to extend this to offer more options. Specifically, I'm looking for "Center" and a version of each existing placement mode where the PopupBox starts at a position that overlaps the popup button (rather than offset away from the button as they are now). This brings me to two questions.

1. First of all, is this functionality even desired? Personally it would be very useful as I think the current options are quite limited. However I am not sure how much customization is in the scope of this control so I ask to make sure.

2. If it is desired, I was wondering about the best way of implementing it. Doing it seems easy enough by extending the `switch (PlacementMode)` that PopupBox.cs currently uses. However, this would quickly make the enum count extremely large and the code as well. I was hoping someone had insight on a better direction to take (eg. maybe an enum for Center but a field for an overlapping option or something like that).

Thanks!

**Comment by Keboo** [comment]
1. This is an interesting requirement. I have no problem merging in a PR for something like this (more on that below), though I am curious to understand the requirements. The PopupBox control is just a convenience wrapper around a toggle button and a popup control. Is there a particular reason you want to cover up that toggle button (making it a little bit harder for the user to dismiss the popup)?

2. Rather than extending the enum I think it might make more sense to simply expose some mechanism to control the placement callback. Perhaps simply expose the [Horizontal/Vertical Offset](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PopupBox.xaml#L106-L107) of the Popup and new dependency properties on the PopupBox? Would that API suit your needs?

**Comment by Anopob** [comment]
Personally I was just looking for a way to make the popup look more "integrated/related" with the button. Regarding the button being hidden, I wanted to avoid that issue by having a new button on top of the popup (but now that I say this, I think maybe this method is too roundabout...). In any case, making the horizontal/vertical offset available to change would be perfect and I think would be exactly what I was looking for.

**Comment by Keboo** [comment]
Great. In that case I think when probably should happen for this is:
- Create new dependency properties on the PopupBox. Something like `PopupHorizontalOffset` and `PopupVerticalOffset`. 
- Add setters to the PopupBox [default style] to default those properties to 5 so we maintain backward compatibility.
- Bind the `HorizontalOffset` and `VerticalOffset` of the Popup to the new properties.
