### ISSUE TITLE
Mahapps NumericUpDown has the same background color as the theme

### ISSUE THREAD

**Issue by ahmediddma** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1416]
Mahapps NumericUpDown has the same background color as the theme (white/dark) unlike the textbox that have transparent background

**Comment by rgomez90** [comment]
@Keboo is this supposed to be this way or is this a bug?

**Comment by Keboo** [comment]
It is probably a bug. Right now we are in a weird place with the MahApps integration as they are making breaking changes to their theme brush names for their 2.0.0 release. My hope is to simply update to MahApps 2.0.0 and fix all of these brush resources. 
As for this specific issue I probably need to look a little closer at it. From the description it sounds like it is a bug since the NumericUpDown control is really designed to be similar to the text box.

**Comment by ahmediddma** [comment]
> 
> 
> It is probably a bug. Right now we are in a weird place with the MahApps integration as they are making breaking changes to their theme brush names for their 2.0.0 release. My hope is to simply update to MahApps 2.0.0 and fix all of these brush resources.
> As for this specific issue I probably need to look a little closer at it. From the description it sounds like it is a bug since the NumericUpDown control is really designed to be similar to the text box.

you can test it by putting a textbox and Mah:NumericUpDown next to each other and changing the background color for the window to any color other than the default theme one

**Comment by Keboo** [comment]
Fixed by #1440

**Comment by ahmediddma** [comment]
@Keboo the validation works it show a red box around the controller but it's much bigger and the message doesn't show
