### ISSUE TITLE
where is DateTimePicker?

### ISSUE THREAD

**Issue by spy0505** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1419]
I need a DateTimePicker,how to do it

**Comment by Keboo** [comment]
There is not a DateTimePicker in this library, only a DatePicker and a TimePicker. You could build something using both of these controls, but there is nothing built in for it. [MahApps](https://github.com/MahApps/MahApps.Metro) does have a DateTimePicker and this library has support for MahApps so that might be the easiest option.

**Comment by spy0505** [comment]
thanks
