### ISSUE TITLE
[Style] How i make text field style return to state "Not Touching" after touching?

### ISSUE THREAD

**Issue by 0rangeFox** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1468]
Hello, im sure about this, is not a error or bug, i wanted to know how i can do this?

On my program, i have a text field, and when i click on it, it appears this style.
https://prnt.sc/pj4v0s

But when i click on outside of text field, thats doesnt dissapear. I need click on random buttons i have placed, and these style disapears, but i wanted to disappear when i click on background of program or something.

https://prnt.sc/pj4wfh

**Comment by jespersh** [comment]
@0rangeFox your links are returning 403 Forbidden

**Comment by 0rangeFox** [comment]
> @0rangeFox your links are returning 403 Forbidden

Oh sorry, didnt noticed that, alright so I fixed that right now.

**Comment by Keboo** [comment]
@0rangeFox I would probably need to see a sample project, but it is possible that this is expected behavior. When the TextBox has focus you will see the TextBox hint displayed like that. Simply tapping off of the TextBox will not change focus unless the element you tap on (such as the button) is focusable. If it is just tapping on the background, that element is likely not focusable and therefore the focus remains with the TextBox.

https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/focus-overview

**Comment by Keboo** [comment]
Also worth mentioning pressing the Tab key should move the keyboard focus away from the Textbox and put you back into the "not focuses" state.
