### ISSUE TITLE
Changing theme is slow

### ISSUE THREAD

**Issue by expelliamus** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1486]
Hi guys,

I have an application with a lot of controls and I've implemented a method for change the primary color of the software as follows:

    private string _theme = "blue";
    public string Theme
    {
        get { return _theme; }
        set
        {
            _theme = value.ToLower();
            OnPropertyChanged();
            var theme = Themes.FirstOrDefault(c => c.Name == _theme);
            new PaletteHelper().ReplacePrimaryColor(theme);
        }
    }

Essentially each time this property is called, the method `ReplacePrimaryColor` is firing, but this method freeze the app for 1-2 seconds delay (depend on the pc). Is there a way to avoid that situation?

Kind regards.

**Comment by Keboo** [comment]
Unfortunately if there are lots of controls this process is likely to be slow since changing the theme updates the application resources and all dynamic resources are then forced to update. I am always looking for way to improve the performance of the library, but micro optimizations are not likely to offset many many dynamic resources needing to be updated.
