### ISSUE TITLE
Can't set custom color theme in App.XAML

### ISSUE THREAD

**Issue by VarunSaiTeja** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1502]
Can't set custom color theme in App.XAML
<materialDesign:CustomColorTheme BaseTheme="Light" Primary="Aqua" Secondary="DarkGreen" />

Getting below error in above line

The value "MaterialDesignThemes.Wpf.CustomColorTheme" is not of type "System.Windows.ResourceDictionary" and cannot be used in this generic collection.

**Comment by VarunSaiTeja** [comment]
2.6.0

Showing error
But executing

**Comment by Keboo** [comment]
This is a known issue with 2.6.0. The `CustomColorTheme` is a markup extension that returns a ResourceDictionary. Unfortunately Visual Studio doesn't realize that so you get a design-time warning. However, because it is in fact returning the correct type it works at runtime. With 3.0.0 this has been changed, instead of using the markup extension these classes derive from `ResourceDictionary` directly which fixes the warning.
