### ISSUE TITLE
DatePicker bounces around.

### ISSUE THREAD

**Issue by steiftier** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1509]
The datepicker bounces around when placed close to the bottom of the screen.

This happens when switching between certain months that have a different number of rows for the days. This changes the height of the popup and thus the placement.
As consequence it is not possible to switch through the months per left/right-buttons without moving the mouse.

![datepicker_bounce](https://user-images.githubusercontent.com/6057035/68667533-7eb71a00-0546-11ea-8834-73bbfeae05f4.gif)

**Comment by Keboo** [comment]
This is caused because of the behavior of the popup control. I am open to suggestions on how to best fix this. I only see a couple reasonable options.
1. In the popup placement callback apply a vertical offset to make room for the extra row to show up.
2. Leave additional whitespace to support a 5th row in the calendar control. I am not sure on this approach as this seems like it would leave a lot of dead space.

**Comment by steiftier** [comment]
You meant the 6th row, I guess.
How about filling the dead space with days of the next month? I don't know how hard this is to implement but that's how some other datepickers deal with this. For example the one in Windows 10 or this example:
![date_picker](https://user-images.githubusercontent.com/6057035/68923407-8f51d500-077e-11ea-8226-316cb4262923.png)

**Comment by Keboo** [comment]
@steiftier yes, sorry a 6th row. 
From going over the [spec](https://material.io/components/pickers/#specs) a little bit more it seems like always having space for the 6th row is the way to go. It seems like there are pickers that go back and forth about whether to fill that row with days from the next month or not. Personally I am not really picky about it and would be happy to look at a PR either way.
