### ISSUE TITLE
Does the project support .NET Standard?

### ISSUE THREAD

**Issue by mincasoft** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1521]
# Does the project support .NET Standard?

I am writing a .NET Standard 2.1 library that uses some of the Material.WPF classes, but the Visual Studio IDE has warned me that the MaterialDesignThemes library may not fully support .NET Standard. I would like to know if this project has a plan to support the .NET Standard platform?

**Comment by Keboo** [comment]
The short version is no. 

Here is the long version. .NET Standard libraries can be consumed by many different runtimes including Mono. This library is really only designed for WPF applications. This means it is expected .NET Framework, or .NET Core 3.0 (assuming you are working with the 3.0.0 preview NuGet packages). For this reason the [underlying projects](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/MaterialDesignThemes.Wpf.csproj#L4) simply [multi-target](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-multitargeting-overview?view=vs-2019) these two platforms. With all of that said if you want to include them in a .NET Standard 2.1 project that is only going to be consumed by a WPF project, then I would expect everything to work. 
Depending on what you are building I would probably recommend one of the following solutions:
- Change your library to multi-target the runtimes that support WPF. I find this to be the simplest solution since it more accurately represents how your package should be consumed. I have an example of doing that [here](https://github.com/Keboo/ShowMeTheXAML/blob/master/ShowMeTheXAML/ShowMeTheXAML.csproj).
- Don't reference the NuGet package directly. Instead use something like [paket](https://fsprojects.github.io/Paket/) or [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) to bring in just the C# files that you need into your project. This solution may not work depending in exactly which files you need.
- Just suppress the warning in Visual Studio. The warning is really only there because this library doesn't declare that it supports .NET Standard. However, if you know .NET Standard library is only going to be used by a WPF project, then you are fine and can ignore it.

**Comment by mincadev** [comment]
Oh yeah! I have converted my project to .NET Core 3.0, and MaterialDesignThemes has very good support. I hope the project has worthwhile improvements in terms of experience

**Comment by nssoft-rlagrange** [comment]
Hi @Keboo ,
I got a similar problem with a "clean" architecture.

Process is a .net core (3.1) wpf app, which instantiante the core multiplatform "app"
Application : is a .net standard library hosted by the prev "process"

The "application" must reference some wpf libraries, for example mvvmlightlibsstdcore, in order to react to user input with relaycommand, etc.

For MaterialDesign, the only reason I have to reference it directly is the ISnackbarMessageQueue interface.
Now, I can't compile the .net standard 2.1 "app" because visual studio can't decide between .netcoreapp and .netframework version... I have to store it as a simple "object", and make calls using reflection in order to not have this reference.

Is it possible to move all interfaces to an "abstractions" sub package (like Microsoft.Extensions.Logging.Abstractions), which should be a .net standard (less possible version) lib that anything can reference ?

Thanks.

**Comment by Keboo** [comment]
@nssoft-rlagrange unfortuently there are so few useful abstractions I don't believe that it is reasonable to move them to an abstractions package. With that said, there is nothing stopping you from creating your own abstractions project with your own interfaces that derive and delegate to the appropriate material design classes.
