### ISSUE TITLE
Issues with DataGrid columns

### ISSUE THREAD

**Issue by ahmediddma** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1573]
the down arrow for the drop down list (at the end of the DataGridComboBoxColumn) is not the same size or position as the ComboBox and  its background can't be set.

validation with INotifyDataErrorInfo for each columns doesn't fully work the column will have red borders but no text.

https://github.com/ahmediddma/WPFDataGridValidationMDIX

**Comment by Keboo** [comment]
The issue here is that the validation template does not match the normal material design:
![image](https://user-images.githubusercontent.com/952248/80447172-88062a00-88cd-11ea-9052-ba44094680ee.png)
This should present as a red underline similar to how the TextBox does:
![image](https://user-images.githubusercontent.com/952248/80447238-b97ef580-88cd-11ea-9baf-5dae15370896.png)

**Comment by greuelpirat** [comment]
> the down arrow for the drop down list (at the end of the DataGridComboBoxColumn) is not the same size or position as the ComboBox and its background can't be set.

is solved with #1789

> validation with INotifyDataErrorInfo for each columns doesn't fully work the column will have red borders but no text.

is solved with #1787
