### ISSUE TITLE
Transparency/placement issue in editable combobox when popup is open

### ISSUE THREAD

**Issue by dmuehlenhoff** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1590]
Hello,

the following issue is reproducible in the demo application, so I have not prepared a demo repo.

Description
-------------
If there is an editable combobox near the bottom of the screen, the calculation of the popup position seems to be incorrect. The normal windows combobox behavior is to have the popup placed above the combobox so that the bottom of the popup aligns with the top of the field. With MaterialDesign, it seems that the bottom of the popup aligns with the bottom of the screen, which leads to a look that is probably not intended.

Steps to reproduce
---------------------
- Open the demo application
- Go to the "Fields" section
- Move the window so that the "At least 8 characters" HelperText of the Password control aligns with a normal height windows taskbar (see screenshot 1)
- Open the "Fruit" combobox

You should be seeing something roughly like screenshot 2. The popup is positioned incorrectly and the transparent part of the popup that should contain the editable textbox of the Fruit combobox now contains the OS combobox. If the popup is supposed to cover the combobox then the transparent part needs to be at the bottom of the popup. In any case, the list of items should all be displayed above the combobox

Thanks for your time in advance,
David

Screenshot 1
![grafik](https://user-images.githubusercontent.com/22953360/71668479-5d65f380-2d69-11ea-9aee-19074d4447a1.png)

Screenshot 2
![grafik](https://user-images.githubusercontent.com/22953360/71668265-889c1300-2d68-11ea-9c78-f8032615006b.png)

**Comment by Echolaitoc** [comment]
In classic mode the popup may conceal the combobox, which is also not desirable. More screenshots from the demo app for classic mode and Material Design mode.
![MaterialDesign_ComboBox_ClassicBroken](https://user-images.githubusercontent.com/3448098/73932930-a87ca480-48db-11ea-8994-ff7a2871a150.png) ![MaterialDesign_ComboBox_DownBroken](https://user-images.githubusercontent.com/3448098/73932931-a9153b00-48db-11ea-88e4-3b8dc0ea8c38.png)

Default Windows ComboBoxes make the popup open above the field in this case, instead of shifting it a few pixels:
![MaterialDesign_ComboBox_WindowsDefault](https://user-images.githubusercontent.com/3448098/73932932-a9153b00-48db-11ea-8b7f-3b6f6424adf2.png)

**Comment by Keboo** [comment]
Worth noting I am only able to reproduce this with my DPI set above 100%
