### ISSUE TITLE
[Feature Request] Please Add material tab control

### ISSUE THREAD

**Issue by HamidRezaAshkiyan** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1616]

**Comment by jespersh** [comment]
In the meantime, see https://github.com/spiegelp/MaterialDesignExtensions/ for TabControl style

**Comment by HamidRezaAshkiyan** [comment]
Very good thnaks. 

But I think it is better to be on main library.

**Comment by ahmedflix25** [comment]
the original maintainer was against it because he has this https://github.com/ButchersBoy/Dragablz

**Comment by Keboo** [comment]
I have raised the question with the original author about including something in the main library. With the addition of additional target platforms it seem like that restriction may need to change. I have raised the concern and am leaving this issue open as a reminder.

**Comment by bebenins** [comment]
Dragablz is sufficient for me, for example.  The only thing I wish it included is control for shadow.  The shadow itself is also not the same as MD library shadow.
Not sure what others are missing, this is just FYI I guess

**Comment by Jesus805** [comment]
Would like to note that Dragablz has not been updated in 2 years. Also, ButchersBoy profile states that he has been taking a break from Open Source. Perhaps it would be worthwhile to implement Material Tab (For people who don't need need the drag out feature)

**Comment by lgreenlee** [comment]
I'd just like to throw a vote in for this - this is a pretty core piece of the Material Design "specification". Given this library provides nearly everything else it should include this as a style. I don't really want to add more dependencies to projects for just one piece of functionality. It even looks like the style was just commented out? Thanks for a great library it has been great to use!

**Comment by ahmed-abdelrazek** [comment]
@Keboo is this coming with v4.4.0?

**Comment by MichelMichels** [comment]
> @Keboo is this coming with v4.4.0?

I don't think any work has been pushed for this issue. You could always send a PR yourself.

**Comment by ahmed-abdelrazek** [comment]
will see what i can do at the weekend

**Comment by Keboo** [comment]
There is actually work that has been done on this. https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TabControl.xaml#L24-L202

It is however, just been left commented out. The reasons for this are historical and a bit convoluted. When I first started maintaining the project the author's guidance was to not include a TabControl style, and Dragablz was expected to fulfil that need. However, because Dragablz is not part of this same org on GitHub it has not received the same level of updates and has fallen behind with notable issues being no theme brush updates for latest MDIX, and no netcore3.1+ support. This is leaving a hole in the library which is where this feature request is coming from.

I think it is probably reasonable to go ahead and uncomment that code (and validate that it is still correct).

**Comment by ahmed-abdelrazek** [comment]
yep that was my plan

**Comment by MichelMichels** [comment]
@ahmed-abdelrazek  and I submitted PR requests to resolve this issue.

**Comment by Keboo** [comment]
Re-opening for now, just until the PR merges into master
