### ISSUE TITLE
Tooltips on materialDesign:PackIcon not displaying when mouse is over pixels not drawned

### ISSUE THREAD

**Issue by gitjsdr26** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1719]
Hi all,
I'm facing a problem with Tooltips on materialDesign:PackIcon.
When the mouse is over a transparent pixel (not drawned) of an icon, the tooltip is not displayed.
See pictures below.

- Tooltip displayed

![Displaying Tooltip](https://user-images.githubusercontent.com/60319431/78195469-f519d180-747f-11ea-9497-2534cee8d366.png)

- Tooltip not displayed

![Not Displaying Tooltip](https://user-images.githubusercontent.com/60319431/78195485-ffd46680-747f-11ea-902f-9c1907c870a9.png)

Regards

**Comment by Keboo** [comment]
Hi @gitjsdr26 this is because the default background of the PackIcon is unset. Though visually, they look the same, the difference is that when unset background (un-drawn) pixels on the PackIcon do not raise mouse events. This is done for performance reasons. If you simply set the Background of your PackIcon to Transparent you should so it work as you expect.

**Comment by gitjsdr26** [comment]
Hi @Keboo , than you for your answer.
I set background to Transparent and now it's working.

```C#
<materialDesign:PackIcon x:Name="iconConnected" Height="20" Width="20" Kind="LinkVariant" 
    Foreground="Gray"
    ToolTip="{Binding ConnectionStatusDescription}"
    VerticalAlignment="Center"
    Background="Transparent"
/>
```

Best regards
