### ISSUE TITLE
SecondaryColor Enum

### ISSUE THREAD

**Issue by devriesb13** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1913]
Hi there,

Can these values be added to the secondary color enum? You can set these color in the color tool demo and would help with persisting settings.

![image](https://user-images.githubusercontent.com/10214916/84345540-02c2a480-abf1-11ea-9dec-8862b4c09c73.png)

Cheers

**Comment by Keboo** [comment]
I don't think that will be possible. The reason those do not exist is because the material design specification does not define accent colors for those. You can see them [in the color tool](https://material.io/resources/color/) (the last four columns are the accent colors).

![image](https://user-images.githubusercontent.com/952248/84604309-ee2d1900-ae49-11ea-8137-6d17151660aa.png)
