### ISSUE TITLE
Would it be possible to have DrawerHost.CenterDrawerContent ?

### ISSUE THREAD

**Issue by gitjsdr26** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1921]
Actually it's possible to have for DrawerHost with `Right`, `Left`, `Top`, `Bottom`, content properties.
Would it be possible to have `DrawerHost.CenterDrawerContent` ?
Indeed, I'd like to make a Wizard using `materialDesign:Transitioner` into a `DrawerHost` centered.
Is it possible to do it or should I use the `materialDesign:DialogHost` to achieve it ?
Regards

**Comment by Keboo** [comment]
I believe the DialogHost is the correct tool for this job, specifically using the [MaterialDesignEmbeddedDialogHost](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/ControlStyleList#dialoghost) style since this will make the dialog part of the visual tree (like what the DrawerHost does).

**Comment by gitjsdr26** [comment]
@Keboo , thank you. This question is linked to the previous one #1924 , because I'd like to make a Wizard but this Wizard will have to popup Dialogboxes.

**Comment by Keboo** [comment]
@gitjsdr26 Wouldn't you want to have a DialogHost hosting the wizard, and then withing the Dialog have a second dialog host for any dialogs that the wizard needs to display?

**Comment by gitjsdr26** [comment]
@Keboo , yes you are right, but i didn't think that it was possible. Thanks.
