### ISSUE TITLE
Changing Theme to light or dark always catch exception

### ISSUE THREAD

**Issue by Noboroto** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2014]
I use this sample at [Advanced Theming
](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Advanced-Theming#changing-the-theme) to change the dark theme in runtime
```cs
using MaterialDesignColors;
using MaterialDesignThemes.Wpf;
...
var paletteHelper = new PaletteHelper();
//Retrieve the app's existing theme
ITheme theme = paletteHelper.GetTheme();

//Change the base theme to Dark
theme.SetBaseTheme(Theme.Dark);
//or theme.SetBaseTheme(Theme.Light);

//Change the app's current theme
paletteHelper.SetTheme(theme);
```
but when run I get this exception
```
System.InvalidOperationException
  Message=Could not locate required resource with key(s) 'SecondaryHueMidBrush, SecondaryAccentBrush'
  Source=MaterialDesignThemes.Wpf
```
see more in [my sample](https://github.com/Noboroto/SampleThrowException)

**Comment by KHALED-LAKEHAL** [comment]
use this method
```
 public static ITheme SetTheme(String primaryColor, String accentColor, Boolean isDarkTheme)
        {
            ITheme theme;
            Color _accentColor = SwatchHelper.Lookup[ToMaterialDesignColor(accentColor)];
            Color _primaryColor = SwatchHelper.Lookup[ToMaterialDesignColor(primaryColor)];
            if (isDarkTheme)
            {
                theme = Theme.Create(new MaterialDesignDarkTheme(), _primaryColor, _accentColor);
            }
            else
            {
                theme = Theme.Create(new MaterialDesignLightTheme(), _primaryColor, _accentColor);
            }
            return theme;
        }

        private static MaterialDesignColor ToMaterialDesignColor(String color)
        {
            return (MaterialDesignColor)Enum.Parse(typeof(MaterialDesignColor), color, false);
        }
```

**Comment by Keboo** [comment]
@Noboroto I believe the issue is that the `PaletteHelper` method act on the application resource dictionary (App.xaml), but your initial setup of the `BundledTheme` is being done inside of the Window resources. 

You have two choices
1. Simply move the theme resource dictionaries to the application level resource dictionary.
2. Don't use the `PaletteHelper` and instead use the `GetTheme` / `SetTheme` extension methods on your Window's resource dictionary. This is effectively what [PaletteHelper does with the application resource dictionary](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/PaletteHelper.cs)
