### ISSUE TITLE
Drawerhost OnOpen/OnClose event?

### ISSUE THREAD

**Issue by KHALED-LAKEHAL** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2015]
Hello how add  Drawerhost OnOpen/OnClose event like dialoghost DialogOpenedEventHandler/DialogClosingEventHandler

**Comment by Keboo** [comment]
Currently it looks like this is simply a feature that is missing. If anyone wants to submit a pull request for it, I would be happy to see about getting it merged.

**Comment by Streissi** [comment]
anyone up to this?, otherwise i will grab it

**Comment by Keboo** [comment]
@Streissi all yours

**Comment by Streissi** [comment]
@Keboo should i add events (opened/closing) for every Drawer Dock position or one general where you get which position raised the event in the event agrs?

I will prefer the second approach, because mostly you have only one drawer in your application and if you have more than one, you can switch by the Dock enum in the event args

**Comment by Keboo** [comment]
I like the second approach as well.
