### ISSUE TITLE
String format of date picker

### ISSUE THREAD

**Issue by Kelb-Tansley** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2042]
How do i set the date pickers string format to 'yyyy-MM-dd' or any other format?

**Comment by SincroB-Dev** [comment]
You can use the String Format on any components.

**Comment by hussain1368** [comment]
setting StringFormat didn't work for me

**Comment by Keboo** [comment]
> setting StringFormat didn't work for me

Often when the `StringFormat` property of a binding does not work, it is because the binding is being applied to a non-string property. The `StringFormat` property will only work when the bound value is displayed as string. [docs](https://learn.microsoft.com/dotnet/api/system.windows.data.bindingbase.stringformat?view=windowsdesktop-7.0)
