### ISSUE TITLE
CCTV footage (IntPtr) not displaying in Dialoghost

### ISSUE THREAD

**Issue by dragonballz96** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2057]
Currently, i am using Hikvision SDK to connect to various cameras. The footage is shown in a Win Forms Picture Box control as stated below:

 <WindowsFormsHost Grid.Row="1" Margin="20 14 20 0">
            <wf:PictureBox x:Name="pbCAMPreview" Width="640" Height="360" />
  </WindowsFormsHost>

I have to pass its pbCAMPreview.Handle (IntPtr) to the SDK function to get the footage. It is working in a normal Window. But, it will not work if I use it in a popup Material Design Dialoghost.

Any advice?

**Comment by Keboo** [comment]
I assume the popup is likely what is causing the issue if the HikVision SDK is expected to be able to get ahold of window handle. Popups are their own lightweight window and separate from the main window. 
There are a couple things I would suggest trying. 

1. Switch to using the embedded dialog host (`Style="{StaticResource MaterialDesignEmbeddedDialogHost}"`). This secondary style embeds the dialog directly inside of the window's visual tree rather than using a popup. The disadvantage here is that the dialog's size cannot exceed the containing window (while the popup allows that). If that restriction is acceptable, that is likely the simples option.

2. Manually parse the visual tree to get the popup control. Depending on how you are setting up the dialog something like this as the DialogOpened event handler can get your the handle for the PopupEx.
```C#
private void DialogHost_DialogOpened(object sender, DialogOpenedEventArgs eventArgs)
{
    IntPtr handle = IntPtr.Zero;
    for (var @do = (DependencyObject)eventArgs.Session.Content;
        @do != null;
        @do = VisualTreeHelper.GetParent(@do) ?? LogicalTreeHelper.GetParent(@do))
    {
        if (@do is Visual visual &&
            PresentationSource.FromVisual(visual) is HwndSource source)
        {
            handle = source.Handle;
            break;
        }
    }
}
```

**Comment by dragonballz96** [comment]
Indeed, you are right. Option 1 is not appealing for my implementation. As for option 2, I am displaying the dialoghost in a View Model using the following code:

var addNewView = new AddNewView(RecId, RecNo);
await DialogHost.Show(addNewView, "RootDialog");

In this case, I am facing another challenge to search the Handle from WindowsFormsHost.Child in the Visual Tree. Do you know how can I do it? I am struggling to create a DependencyObject for WindowsFormsHost which will have a method to get PictureBox.Handle.

Let me know. Thanks.

**Comment by dragonballz96** [comment]
> I assume the popup is likely what is causing the issue if the HikVision SDK is expected to be able to get ahold of window handle. Popups are their own lightweight window and separate from the main window.
> There are a couple things I would suggest trying.
> 
> 1. Switch to using the embedded dialog host (`Style="{StaticResource MaterialDesignEmbeddedDialogHost}"`). This secondary style embeds the dialog directly inside of the window's visual tree rather than using a popup. The disadvantage here is that the dialog's size cannot exceed the containing window (while the popup allows that). If that restriction is acceptable, that is likely the simples option.
> 2. Manually parse the visual tree to get the popup control. Depending on how you are setting up the dialog something like this as the DialogOpened event handler can get your the handle for the PopupEx.
> 
> ```cs
> private void DialogHost_DialogOpened(object sender, DialogOpenedEventArgs eventArgs)
> {
>     IntPtr handle = IntPtr.Zero;
>     for (var @do = (DependencyObject)eventArgs.Session.Content;
>         @do != null;
>         @do = VisualTreeHelper.GetParent(@do) ?? LogicalTreeHelper.GetParent(@do))
>     {
>         if (@do is Visual visual &&
>             PresentationSource.FromVisual(visual) is HwndSource source)
>         {
>             handle = source.Handle;
>             break;
>         }
>     }
> }
> ```
Indeed, you are right. Option 1 is not appealing for my implementation. As for option 2, I am displaying the dialoghost in a View Model using the following code:

var addNewView = new AddNewView(RecId, RecNo);
await DialogHost.Show(addNewView, "RootDialog");

In this case, I am facing another challenge to search the Handle from WindowsFormsHost.Child in the Visual Tree. Do you know how can I do it? I am struggling to create a DependencyObject for WindowsFormsHost which will have a method to get PictureBox.Handle.

Let me know. Thanks.

**Comment by Keboo** [comment]
Hi @dragonballz96 I am not sure I understand the problem. The `WindowsFormsHost`'s base class is a `DependencyOpject` so you should be able to simply cast it. 
If you are displaying the dialog using a view model and templates there are only a couple options. 
1) Put something in the code behind that looks up the `IntPtr` and sets it on some property on the view model
2) Start from the `DialogHost` and rather than going up through the visual tree, work down from the dialog host looking for the `PopupEx` control. Once you find the popup you will want to access its `.Child` and once again parse its visual tree looking for the `WindowsFormsHost`

**Comment by dragonballz96** [comment]
> Hi @dragonballz96 I am not sure I understand the problem. The `WindowsFormsHost`'s base class is a `DependencyOpject` so you should be able to simply cast it.
> If you are displaying the dialog using a view model and templates there are only a couple options.
> 
> 1. Put something in the code behind that looks up the `IntPtr` and sets it on some property on the view model
> 2. Start from the `DialogHost` and rather than going up through the visual tree, work down from the dialog host looking for the `PopupEx` control. Once you find the popup you will want to access its `.Child` and once again parse its visual tree looking for the `WindowsFormsHost`

Hi Kevin,

I have been trying various ways to get the handle but the footage is still not displayed. Apparently, I realized that even static Win Form PictureBox or Label won't work in MD Dialoghost:

xmlns:wf="clr-namespace:System.Windows.Forms;assembly=System.Windows.Forms" 

<WindowsFormsHost Grid.Row="1">
<WindowsFormsHost.Child>
                <wf:PictureBox x:Name="pbCAMPreview" ImageLocation="https://upload.wikimedia.org/wikipedia/commons/3/30/Googlelogo.png" Width="600" Height="300"  />
            </WindowsFormsHost.Child>
</WindowsFormsHost>

<WindowsFormsHost Grid.Row="0">
                    <WindowsFormsHost.Child>
                        <wf:Label Text="Why not working?" />
                    </WindowsFormsHost.Child>
                </WindowsFormsHost>

In this case, do you have any advice? Let me know. Thanks.

Ryan
