### ISSUE TITLE
FloatingHintComboBox looses hint

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2066]
From the demo application:
![278867ce-dd8d-438c-8347-d72321023d78](https://user-images.githubusercontent.com/952248/93706012-22fadd00-fad7-11ea-8b82-cdff95a68907.gif)

After selecting a value the hint disappears.
Version 3.2.0-ci1966

**Comment by hackf5** [comment]
This appears to be the expected behaviour. In `MaterialDesignThemes.Wpf\ComboBoxAssist.cs` there is a helpful comment:

``` C#
/// <summary>
/// By default the selected item is hidden from the drop down list, as per Material Design specifications. 
/// To revert to a more classic Windows desktop behaviour, and show the currently selected item again in the drop
/// down, set this attached propety to true.
/// </summary>
public static readonly DependencyProperty ShowSelectedItemProperty = DependencyProperty.RegisterAttached(
    "ShowSelectedItem",
    typeof(bool),
    typeof(ComboBoxAssist),
    new FrameworkPropertyMetadata(false,
        FrameworkPropertyMetadataOptions.AffectsRender | FrameworkPropertyMetadataOptions.Inherits));
```

This behaviour has been implemented in `<Style x:Key="MaterialDesignComboBox" TargetType="{x:Type ComboBox}">` so that the selected item is only visible by default when the combo is editable.

``` XAML
<Trigger Property="IsEditable" Value="True">
    <Setter Property="IsTabStop" Value="False" />
    <!-- designer prefers hard bool -->
    <Setter Property="wpf:ComboBoxAssist.ShowSelectedItem" Value="{StaticResource TrueValue}" />
</Trigger>
```

It took a little while for me to work out how it was doing this, but it is done with a rather sneaky switch of template styles where the default style is to collapse the selected item.

**Based on this my vote would be to close this bug as expected behaviour.**

**Comment by jsinsel** [comment]
This is happening now for a lot of our users after upgrading to 3.2.  The hint text disappears when you select an item for a combo box.

**Comment by SirUppyPancakes** [comment]
Is there a workaround to get the hint showing again before the 4.0.0 release?
The only thing I can come up with is copy-pasting the entire style/template and making the changes from the above pull-request which I'd really like to avoid if possible...

**Comment by MichelMichels** [comment]
This problem has been reintroduced with version 4.1.0. 
When downgrading to 4.0.0 the bug is gone. I will try to look into what is causing this problem. In the meantime, I'll use 4.0.0.
