### ISSUE TITLE
Updated MaterialDesignThemes to 3.2.0, ButtonAssist no longer exists and BundledTheme does not exist, and more

### ISSUE THREAD

**Issue by DevloperRyan** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2189]
My solution targets 4.7.2, and I'm using Visual Studio 2017.

I've uninstalled and reinstalled, still no dice.

I was previously on MaterialDesignThemes 2.6.0 where everything worked.

![image](https://user-images.githubusercontent.com/31998192/101725172-bfe56a80-3a75-11eb-96dc-962d01dba627.png)

These are all of the errors preventing me from building after updating.

**Comment by Keboo** [comment]
Hi @Ryyval 
Can you check your output logs. First increase the output level to Detailed by going to Tools>>Options>>Build and Run and changed the drop down under MSProject build output verbosity.

I suspect there is some compile error that is causing you see those errors.

**Comment by Ryyval** [comment]
Keboo, I don't want to keep you waiting. Since the update didn't work, I've slated the update for a later time until I can gain more information on why it's not working , which is why I posted here.

I will take what you said and do that , but it won't be this week. I'll respond here when I get a chance to perform an update once again, thanks man 👍

**Comment by Keboo** [comment]
@Ryyval no problem. Thanks for the update.
