### ISSUE TITLE
How to extend functionality of controls

### ISSUE THREAD

**Issue by hussain1368** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2195]
Hi,
Is there any way to extend the functionality of any of the controls. For example I need to add persian date to the Datepicker control.
Appreciate if you can guide how to do that

**Comment by Keboo** [comment]
Because this library mostly consists of styles for the built-in WPF controls, you are limited to the functionality provided by those controls. I would suggest taking a look at [handyControls](https://github.com/ghost1372/handyControls) or [PersianToolkit](https://github.com/ghost1372/PersianToolkit) to get a control that supports what you need. 

From there you will likely need to create a new control template for those controls based on the [one in this library](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DatePicker.xaml).

**Comment by hussain1368** [comment]
Reopening this thread if you don't mind. What is the easiest way to apply the style from MaterialDesignInXamlToolkit to PersianCalendar and PersianDatePicker controls from HandyControls?
