### ISSUE TITLE
Incorrect floating hint position on outlined text box

### ISSUE THREAD

**Issue by jizc** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2203]
After #2193, anytime an outlined text box is not the default height (like with multiline text, or when a fixed height is set), the floating hint is not positioned correctly.

This screenshot is from the `Fields` page in the demo app, where the text box `Height` is set to `100`.
![image](https://user-images.githubusercontent.com/1404846/103470123-4ab43f00-4d6e-11eb-8ec0-87e1e025bcc8.png)

Here is a gif of the same text box where I have removed the fixed height. All I'm doing is adding blank lines:
![outlined-text-box-issue](https://user-images.githubusercontent.com/1404846/103470366-d7acc780-4d71-11eb-9082-f4e31712069a.gif)

The issue seems to be due to the [changes in `FloatingHintOffsetCalculationConverter`](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/2193/files#diff-05aa82b654deebd26021c919971fad704499b6adddb9f4bbd55641b55c94b5cd).

**Comment by MichelMichels** [comment]
This is indeed a bug. But the problem isn't in the converter (but I also don't like the changes that were made to this converter, imo it's less readable now and there's more comments).

The problem resides in the MaterialDesignTheme.TextBox.xaml file. On line 241 and below you'll find following snippet:
```xml
<MultiBinding Converter="{StaticResource FloatingHintOffsetCalculationConverter}">
    <Binding RelativeSource="{RelativeSource TemplatedParent}" Path="FontFamily" />
    <Binding RelativeSource="{RelativeSource TemplatedParent}" Path="FontSize" />
    <Binding RelativeSource="{RelativeSource TemplatedParent}" Path="(wpf:HintAssist.FloatingScale)" />
    <Binding RelativeSource="{RelativeSource TemplatedParent}" Path="ActualHeight" />
</MultiBinding>
```
The problem lies in the last Binding in the MultiBinding. When changing the Path property to `Padding`, the bug is fixed. I don't think the ActualHeight is needed to calculate the offset of the hint.

**Comment by jizc** [comment]
Thank you for looking into it and submitting a PR 🎉
