### ISSUE TITLE
Feature request, multi select tree items

### ISSUE THREAD

**Issue by ottosson** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2257]
Hi! Thanks for this awesome library! Really makes WPF apps pretty!

I would like to make a feature request for multi selection in trees.
Just regular CTRL+Click/Shift+click behavior to select/deselect multiple items in the tree would be very useful!

Thanks!

**Comment by ImagineTheGames** [comment]
I would really like this feature as well, would be a tremendous time saver

**Comment by MichelMichels** [comment]
I was researching this topic to see if it's viable to implement and I came across [this StackOverflow thread](https://stackoverflow.com/questions/459375/customizing-the-treeview-to-allow-multi-select).
It reaffirmed my initial response that this seems UI-wise a suboptimal decision and it seems dificicult to implement as the TreeView control does not natively supports multi-selection behaviour.

My proposal would be to reject this suggestion.

**Comment by Keboo** [comment]
I can agree, because the `TreeView` is a built-in WPF control that is outside of this library's control this is a bit out of scope. There are options for adding such behavior to your own `TreeView` controls though. The behavior approach presented [here](https://www.codecadwallader.com/2015/11/22/wpf-treeview-with-multi-select/) appears to be a nice example.
