### ISSUE TITLE
Please don't unnecessarily mark classes as internal (particularly classes used in the XAML templates/styles)

### ISSUE THREAD

**Issue by SirUppyPancakes** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2270]
As I'm working on upgrading to v4.0.0 from v3.1.3, part of my process involves copying/pasting the templates of the controls that I've highly customized for my projects in order to gain complete control over the full look-and-feel.

Unfortunately, some of the classes in this library are marked `internal` (seemingly for no reason, but I could be missing some key aspect of this), and so I have to then copy the source of that class as well and point it to my copy.

Example (at the top of `MaterialDesignTheme.TextBox.xaml`):
```xml
    <converters:TextFieldClearButtonVisibilityConverter x:Key="ClearButtonVisibilityConverter" />
```
where `TextFieldClearButtonVisibilityConverter` is `internal` and so I have to copy/paste the source when customizing this file.

If all converters (and other supporting utilities referenced by the templates/styles) could be marked as public, this would save a good bit of time during upgrades.

**Comment by Keboo** [comment]
Part of the reason for marking classes as internal rather than public is to keep the public API simpler. Many of those converters don't do much (or any error checking of their parameters), lack documentation, and highly specific to a given templates implements. This makes them less than ideal to be part of the library's public API. 
Often the contents of a control's template is treated as an implementation detail therefore not considered public. This is why many of the converters that are intended to simply support that template are marked as internal. I am not opposed to making more of the converters public, though ones like `TextFieldClearButtonVisibilityConverter` would need to be updated to handle error cases; and ideally unit tests.

**Comment by SirUppyPancakes** [comment]
You definitely make some fair points, and it seems that the existing XAML practices around producing and consuming libraries may just be at odds with those around clean APIs and composable code. It isn't an ideal situation, but I can respect the choice to leave some things internal in favor of retaining a cleaner public API.

XAML does offer quite a lot of benefits, so I suppose I'll just have to accept its flaws when it comes to stuff like this; and it helps that I only really have to hack around with it during big upgrades. Thanks for taking the time to reply and explain the choice! Feel free to close this as you see fit.

**Comment by Keboo** [comment]
I do appreciate the feedback. I was not aware many people were copying the styles into their own projects so I will try to be conscious of that workflow going forward to avoid making things difficult.
