### ISSUE TITLE
Dialogs stop rendering sometimes

### ISSUE THREAD

**Issue by andreyea** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2306]
I use Material in Excel addin dialogs. I all works fine, but sometimes the dialog may become unresponsive. If I close it and open it again, the whole thing is just blank and to make it work I need to restart the application. I cannot figure out what may cause this and I see no any errors during debugging. I just wonder if anyone else experienced this issue.

Thanks.

**Comment by andreyea** [comment]
I do have async code inside these dialogs.

The dialogs are just window classes which are displayed using ShowDialog methods. 

Is there any specific way to display a dialog which uses MaterialDesign?

**Comment by andreyea** [comment]
Hi @Keboo ,

I have read more about what are DialogHosts and no, I don't use them at all.

I only have windows which are called from Excel ribbon and I just use elements from Material XAML to style the form.

I notice, this may happen after Excel is being idle for some time and then when I open one of the windows elements are not responsive, dragging the window becomes slow. When close and reopen it again, the whole window is just blank.

Is there a way to debug this?

Thanks

**Comment by Keboo** [comment]
A couple of thoughts. Typically the behavior you are describing is caused because the UI thread is unable to process events. This either occurs because it is blocked/deadlocked or when it gets caught in an infinite loop (or long CPU load) on the UI thread. Being an Excel add-in certainly makes the problem much more difficult to debug. Though I am not too familiar with building these add-ins, I would expect that Excel isolates each extension to keep them from interfering with the main application, which is why are you still able to close the window. 
A few thoughts and ideas that might help.

1. You commented on the RAM usage, but what does the CPU do during this time? Given that we are either looking for a deadlock or an infinite loop it is often helpful to know which case to be looking for. If the CPU usage for the process stays low/idle you are likely looking for a deadlock; otherwise a long running process or infinite loop. 
2. Is the ShowDialog() calls on the window strictly necessary or could you use Show()? ShowDialog is a blocking call, and since the problem could be related to the UI thread being blocked and that is a block UI call, it could be related to that.
3.  Are you able to [launch and attach a debugger to it](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/attach-debugger-from-task-pane)? If this is possible, it would be good to pause the process in the debugger and investigate the [call stack of each of the threads](https://docs.microsoft.com/en-us/visualstudio/debugger/walkthrough-debugging-a-multithreaded-application?view=vs-2019). This might help shed some light on what is happening.
4. This is a bit of a long shot, but are you able to attach [snoop](https://github.com/snoopwpf/snoopwpf) to the window when the problem occurs? Often if the UI thread is hung snoop wont be able to, but the fact you are able to close the window makes me curious if this would work (being unfamiliar with the isolation in Office Add-Ins I am not really sure what will happen).
