### ISSUE TITLE
Add the ability to disable the clock header of TimePicker

### ISSUE THREAD

**Issue by Drise13** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2317]
Looking for a dependency property in TimePicker to toggle the "header clock" section of the time picker:

![image](https://user-images.githubusercontent.com/10517125/117224382-65a6c680-add5-11eb-8d99-a081e085f0ef.png)

**Comment by Keboo** [comment]
This header is part of the [clock template](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Clock.xaml#L392-L448). Since the [Clock](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Clock.cs) is a custom control for this library I would expect that this could be a dependency property directly on that control. This would then need to be exposed through the TimePicker as well. Because the TimePicker is also a custom control in this library I would also expect that to be exposed as a dependency property there as well.
