### ISSUE TITLE
how to set Menu and MenuItem background and foreground color when mouse over

### ISSUE THREAD

**Issue by stanley8615** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2366]
![image](https://user-images.githubusercontent.com/18675061/124695625-26503f80-df16-11eb-85d4-2e34ed039335.png)
some control like Menu,MenuItem,ListBox,ListView,Datagrid ... background and foreground when mouse over, color is gary  , how to set that colors by one time, not custom style(trigger) one by one, thanks

**Comment by Erapchu** [comment]
Hello!
If you want just set background color as gray, you can use a property "Background" for controls that you want.

**Comment by stanley8615** [comment]
> Hello!
> If you want just set background color as gray, you can use a property "Background" for controls that you want.

Thanks
But that's not what I mean,I mean  under “Mouse Over” ,like Highlight or Active color

**Comment by Keboo** [comment]
@stanley8615 so you listed several controls up there. Each is going to have slightly different answers.

For Menu/MenuItems: These are not currently settable. They are [controlled indirectly by the Foreground brush](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/tree/8b62ab4d811a2790fac97339ecbc1b84538a272c/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Menu.xaml#L119-L124). This color than has an [opacity set](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/8b62ab4d811a2790fac97339ecbc1b84538a272c/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Menu.xaml#L291-L293) when the mouse is over.
ListBox/ListView: Similar story here. These are [controlled by the Foreground](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/8b62ab4d811a2790fac97339ecbc1b84538a272c/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ListBox.xaml#L111-L113). There is a bit of a hack [I posted](https://github.com/Keboo/MaterialDesignInXaml.Examples/blob/master/ListBox/ListBox.Colors/MainWindow.xaml#L16-L26) that manipulate the contents of the control template at runtime, but due to the triggers the opacity still applies.
DataGrid: You are in more luck here these are [controlled by the theme brush `MaterialDesignSelection`](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/8b62ab4d811a2790fac97339ecbc1b84538a272c/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DataGrid.xaml#L206). If you want to change the theme brush the docs are [in the wiki](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Advanced-Theming) or I have some [samples online](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/Theming/Theme.CustomColors)

**Comment by stanley8615** [comment]
> @stanley8615 so you listed several controls up there. Each is going to have slightly different answers.
> 
> For Menu/MenuItems: These are not currently settable. They are [controlled indirectly by the Foreground brush](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/tree/8b62ab4d811a2790fac97339ecbc1b84538a272c/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Menu.xaml#L119-L124). This color than has an [opacity set](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/8b62ab4d811a2790fac97339ecbc1b84538a272c/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Menu.xaml#L291-L293) when the mouse is over.
> ListBox/ListView: Similar story here. These are [controlled by the Foreground](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/8b62ab4d811a2790fac97339ecbc1b84538a272c/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ListBox.xaml#L111-L113). There is a bit of a hack [I posted](https://github.com/Keboo/MaterialDesignInXaml.Examples/blob/master/ListBox/ListBox.Colors/MainWindow.xaml#L16-L26) that manipulate the contents of the control template at runtime, but due to the triggers the opacity still applies.
> DataGrid: You are in more luck here these are [controlled by the theme brush `MaterialDesignSelection`](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/8b62ab4d811a2790fac97339ecbc1b84538a272c/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DataGrid.xaml#L206). If you want to change the theme brush the docs are [in the wiki](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Advanced-Theming) or I have some [samples online](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/Theming/Theme.CustomColors)

Thanks a lot ~!
by the way
![image](https://user-images.githubusercontent.com/18675061/124705839-dd55b680-df28-11eb-8260-a906c68c20d8.png)
I tried to change "SystemColors.XXXX" but not work, I think maybe link systemcolors is  a options to solve this problem

**Comment by Keboo** [comment]
I have added it to the [list of changes to be considered for the 5.0.0 release](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/2255). Having more control over individual colors is something that has been requested a lot so I want to spend some time going through the controls and providing that control to enable code like what you have above.

**Comment by stanley8615** [comment]
This WPF UI is great, I look forward to your next version very much
thank you
