### ISSUE TITLE
WPF UI Freezes after resuming from screen lock for slider

### ISSUE THREAD

**Issue by Divyesh-13** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2473]
Hello,

In the application when screen lock after unlock application is freezes if slider is remove then application work normally

**Comment by Erapchu** [comment]
Probably some other controls uses bitmap cache too. To detect it you need to search over all controls in XAML of you window. 
You need to:
1) Find control with bitmapcache
2) Remove bitmapcache in style
3) Set that style to control
I can't help without more info. Please if you can send a link to project or send code here. Otherwise, you need just to find all controls with bitmapcache and remove them, see what's happens. Only MaterialDesignToolBar and Sliders use BitmapCache that cann't be controlled via ShadowAssist.CacheMode

**Comment by Divyesh-13** [comment]
this is a demo project
https://github.com/Divyesh-13/test

**Comment by Erapchu** [comment]
@Divyesh-13 please make this repository as public or check a link.

**Comment by Divyesh-13** [comment]
Sorry now check
click on login button and lock screen then try to change value for slider

**Comment by Erapchu** [comment]
This is a known issue https://github.com/Erapchu/GhostWindows
You need to avoid hide WPF windows at all. You may close first window and open second one. The root of this behavior is BitmapCache

**Comment by Divyesh-13** [comment]
ok thankyou
