### ISSUE TITLE
PackIconKind Skip is changed

### ISSUE THREAD

**Issue by kristoffer-tungland** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2486]
We are currently using the PackIconKind Skip i our app, but after changing to version 4.2.1 the icon was swapped to Basket.

The enum in master is Skip=Basket, but in version 4.1.0 it was Skip=DebugStepOver.

Was this change a mistake or intended?

Link to code:

Version 4.1.0
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/3ac914f6f77a3bde3a56f6c92aaaa90fa1ae7af0/MaterialDesignThemes.Wpf/PackIconKind.cs#L3636 

Version 4.2.1
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/413d7a3cdca88c01b40360998d083a7ad7c18236/MaterialDesignThemes.Wpf/PackIconKind.cs#L1591

**Comment by Keboo** [comment]
It was sort of both. 
The PackIcons [are generated](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/.github/workflows/icon_update.yml) from https://materialdesignicons.com/. Unfortunately when there are changes there, it can cause issues like what you observed. It doesn't happen often but it does occur.

Because these are all auto-generated it is non-trivial to avoid breaking changes when icons change. As a middle ground I have scripted out the [PackIcon release notes](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/PackIcon-ReleaseNotes) so that there is at least documentation of which icons are added/removed/changed.
