### ISSUE TITLE
Suggestions for DataGrids

### ISSUE THREAD

**Issue by Xaalek** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2500]
I have some suggestions to improve the user experience with datagrids.

### 1)
The first one is to add TextTrimming on DataGridRows.
As you can see bellow, the Header has a TextTrimming but not the rows.
![image](https://user-images.githubusercontent.com/54487782/143278983-e555ceef-bfdb-433f-9315-18246fd58df6.png)

I know we can change this with a piece of code :
```
<Setter Property="TextTrimming" Value="CharacterEllipsis"/>
```
It would be nice if it was implemented by default with the library.

### 2)
My second suggestion is to add a vertical line to delimit the column size when `CanUserResizeColumns` is true.

Today it's hard the find the right spot for resizing a column.

I know we can change `GridLinesVisibility` but I find this ugly.
Example with `GridLinesVisibility="All"` :
![image](https://user-images.githubusercontent.com/54487782/143282448-44ad59e6-3186-4d2b-a018-6a7edcbf87f2.png)

A good improvement would be something like this :
![image](https://user-images.githubusercontent.com/54487782/143281887-a840cbe3-c822-4bc0-a3bf-4c3a2631c605.png)
You can take a look on this page : https://mui.com/components/data-grid/

### 3)
My last suggestion is to add the possibility to scroll horizontally with the mouse wheel.

In a lot of applications we can scroll horizontally with **shift+mouse wheel** but not in WPF.
It would be a nice feature for DataGrids especially when we have a lot of data to display.

**Comment by Erapchu** [comment]
I think the proposed improvements are very necessary for DataGrid control. TextTrimming is required option because of invisible delimiters between columns.

**Comment by Keboo** [comment]
So addressing these one at a time.

1) Completely agree, this is something that should be turned on by default.

2) The reason that there are no vertical separators on by default is the [Material Design v2 spec](https://material.io/components/data-tables) does not contain them. However, this is only the default setting. The DataGrid contains a property named `GridLinesVisibility` simply setting to be `All` should get you the look you are going for.

3) In WPF control are often [described as "lookless"](https://wpf.2000things.com/2014/08/14/1136-wpf-controls-are-lookless/). This means there is a separation between how a control looks (via its template) and how it behaves (the code). This library really aims to mostly cover the look of the controls, and tries to be agnostic to anything else that a developer might want to bring into their projects. For dealing with things like horizontal scroll, I would expect projects to implement something like a [Behavior](https://www.wpf-controls.com/behaviors-and-attached-properties/) to handle things like scrolling. There is also an outstanding feature request to add in support for this to WPF (which would be a better place for a complete solution). You can upvote the issue here: https://github.com/dotnet/wpf/issues/3201
