### ISSUE TITLE
Regression : When a TextBox Floating Hint contains multiple lines, text is over the Floating Hint text.

### ISSUE THREAD

**Issue by gitjsdr26** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2514]
When a TextBox Floating Hint contains multiple lines, the TextBox text is over the Floating Hint text that make the Floating Hint text not readable.
![image](https://user-images.githubusercontent.com/60319431/144652164-fbd9336e-02ea-4435-a7e8-1464a9d94229.png)

This is a regression in v4.3.0, because the same issue has already been solved in #2344 and #2352.

**Comment by Erapchu** [comment]
I would like to say, that TextBox with floating hint by design should NOT contains multiple lines or trimmed text. Such a text is simply hard to read.

![image](https://user-images.githubusercontent.com/37536541/144779583-c5afec47-2081-41c1-86a2-fcbb309d0777.png)

https://material.io/components/text-fields#anatomy

Please, for all additional info use helper text - HintAssist.HelperText.

![image](https://user-images.githubusercontent.com/37536541/144779880-db647631-9191-47e4-8aff-2a02e86282d0.png)

**Comment by gitjsdr26** [comment]
I do not agree with this, especially since this problem had already been corrected in commit c6b398d for issue #2352.
But see the Build, it seems to have failed.

![image](https://user-images.githubusercontent.com/60319431/144813473-3997c131-9a6b-43d8-ae01-5ea6781690bf.png)

**Comment by Erapchu** [comment]
You can also set HintAssist.FloatingOffset for this

**Comment by MichelMichels** [comment]
> I do not agree with this, especially since this problem had already been corrected in commit c6b398d for issue #2352.
> But see the Build, it seems to have failed.
> 
> ![image](https://user-images.githubusercontent.com/60319431/144813473-3997c131-9a6b-43d8-ae01-5ea6781690bf.png)
> 

It's not something to agree with or not. As @Erapchu mentioned, the material design specification is very clear in disallowing what you want to achieve.

As for the build fail, there was a flaky test that @Keboo fixed a couple of days ago which made builds randomly fail.

I'd vote to follow the material specification and not support this.
