### ISSUE TITLE
Bad interaction between OxyPlot and Dialogs

### ISSUE THREAD

**Issue by yoann-arseneau** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2529]
Hi, I encountered an issue where an OxyPlot.PlotView will be blank when shown in a DialogHost's DialogContent. Any insight into what might be causing this interaction would be appreciated.

I illustrate the issue in [this repo](https://github.com/yoann-arseneau/OxyDialogTest/tree/master).

**Comment by Keboo** [comment]
Thank you for the nice repo project. It is very helpful. Unfortuently this does not appear to be an issue with this library, and instead appears to be an issue with the OxyPlot library not supporting Popups.
You can confirm this by simply putting the PlotView inside of a Popup control:

```xaml
<Popup x:Name="MyPopup">
  <Grid Width="500" Height="500">
    <Grid.RowDefinitions>
      <RowDefinition/>
      <RowDefinition Height="Auto"/>
    </Grid.RowDefinitions>

    <oxy:PlotView Grid.Row="0" Model="{Binding DialogPlot}"/>
    <StackPanel Grid.Row="1" Orientation="Horizontal" HorizontalAlignment="Center">
      <Button Command="{Binding SwapCommand}">Swap</Button>
      <Button Command="{x:Static md:DialogHost.CloseDialogCommand}">Close</Button>
    </StackPanel>
  </Grid>
</Popup>
``` 
In a button click handler you can simply do the following:
```C#
private void Button_Click(object sender, RoutedEventArgs e)
{
    MyPopup.IsOpen = true;
}
```

I believe the issue is with the OxyPlot library. I suspect it is the same issue here: https://github.com/oxyplot/oxyplot/issues/1796. However, it does not appear there has been a public release of the library since that fix was put in. You might need to compile the library from source, or inquire on that project when the next release will happen.

**Comment by yoann-arseneau** [comment]
Thanks for the prompt and detailed reply! :)

**Comment by Erapchu** [comment]
@yoann-arseneau Keboo was right. As a simple workaround you can use `Style="{StaticResource MaterialDesignEmbeddedDialogHost}"` for DialogHost
![image](https://user-images.githubusercontent.com/37536541/146739277-0c88e0b0-c9b8-4474-92a4-e21caa6b38a3.png)

Thanks, @Keboo for that
