### ISSUE TITLE
Question : Shadow Assist Animation

### ISSUE THREAD

**Issue by Xaalek** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2650]
I'm trying to create a Dependency Property for the animation duration in the Shadow Assist class but I have a behavior that I don't understand.

Here is the xaml code for my test :
```
<StackPanel
    Grid.Row="12"
    Orientation="Horizontal">
    <Button materialDesign:ShadowAssist.ShadowAnimationDuration="0" Margin="0,0,20,0">Instant</Button>
    <Button Margin="0,0,20,0">Default</Button>
    <Button materialDesign:ShadowAssist.ShadowAnimationDuration="2000" Cursor="Hand">Long</Button>
</StackPanel>
```

As you can see the `materialDesign:ShadowAssist.ShadowAnimationDuration` is set to 2000 (ms) in the xaml code.

Confirmation with Snoop :

![image](https://user-images.githubusercontent.com/54487782/164246472-04f4968c-8f69-410e-adf2-7468b89861e7.png)

But when I hover the button, you can see in the `DarkenPropertyChangedCallback` function that the value 180 is get.
The program get the default value instead of the value contained in the dependency property.

![image](https://user-images.githubusercontent.com/54487782/164246909-85b9c236-f9f1-4e95-9f0b-e96a281f252b.png)

I don't understand why it doesn't work.

Here’s the code I added :

```
       private const double DefaultShadowAnimationDuration = (double)180;

       public static readonly DependencyProperty ShadowAnimationDurationProperty =
            DependencyProperty.RegisterAttached(
                name: "ShadowAnimationDuration",
                propertyType: typeof(double),
                ownerType: typeof(ShadowAssist),
                defaultMetadata: new PropertyMetadata(
                    defaultValue: DefaultShadowAnimationDuration,
                    propertyChangedCallback: new PropertyChangedCallback(OnShadowAnimationDurationChanged))
                );

        public static void SetShadowAnimationDuration(DependencyObject element, double value)
        {
            element.SetValue(ShadowAnimationDurationProperty, value);
        }
        public static double GetShadowAnimationDuration(DependencyObject element)
        {
            return (double)element.GetValue(ShadowAnimationDurationProperty);
        }

        private static void OnShadowAnimationDurationChanged(DependencyObject depObj, DependencyPropertyChangedEventArgs e)
        {
            SetShadowAnimationDuration(depObj, (double)e.NewValue);
        }
```

Related issues : 
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/2355
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/2339

**Comment by Keboo** [comment]
I suspect the issue is the `uiElement` value in the `DarkenPropertyChangedCallback` is not the `Button`. So when you call `GetShadowAnimationDuration` you end up simply getting the default value of the attached property (which is where the 180 is coming from). My guess is it is likely the internal border control from the button's template.

In terms of fixing it, there are two likely solutions:
1. You can make your attached property [inherit](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/properties/property-value-inheritance?view=netdesktop-6.0#making-a-custom-property-inheritable) allowing it to be set at any parent level and have it propagate down to all children.
2. Assuming I am right about the UI element in the Darken property callback being the internal border control, you can forward the attached property's value down on the relevant control. You can see examples of this on the Button's control template with the ButtonProgressAssist attached properties.

**Comment by Xaalek** [comment]
Thank you ! Yes you are right, the UIElement is a border. How can Iforward the attached property's value down on the relevant control ?

**Comment by Xaalek** [comment]
Never mind, I think I've done it.
I'll add what I did in the demo and clean up the code a bit
