### ISSUE TITLE
Listbox inside a scrollviewer doesn't scroll with mouse wheel unless mouse pointer on the scrollbar.

### ISSUE THREAD

**Issue by darcome** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2693]
I simply have placed a listbox inside a scrollviewer with a fixed height nad when I hover over it with the mouse wheel it doesn't scroll unless the mouse pointer is over the scrollbar on the right.

You can find the repo here: 

https://github.com/darcome/MDTDemo

The original problem I had was the scrollviewer inside a groupbox so I have provided an example of that too, but the end result doesn't change.

Thanks in advance

**Comment by darcome** [comment]
Hello, any thouthgts on this problem?

Is there something  else I can do to help you guys out?

Thanks in advance!

**Comment by Keboo** [comment]
Hi @darcome 

I took a look at the repository, what is happening is the `ListBox` itself contains a `ScrollViewer`. By putting a `ListBox` inside of a `ScrollViewer` it is allowing the `ListBox` to increase in size to contain all of its contents (meaning its internal `ScrollViewer` does not display its scroll bars). However, with the fixed size of your `ScrollViewer` it sees the `ListBox` as larger than itself, and displays a scroll bar. Unfortunately, with ScrollViewers, the innermost one will be the one that first receives (and marks as handled) the mouse wheel event. So when you use the mouse wheel, the ListBox's ScrollViewer is receiving and handling that event by doing nothing since it does needs to scroll. It is big enough to contain all of the rows. Because it marks the event as handled, it is ignored by the outer `ScrollViewer`. When you hover over the scroll bar and use your mouse wheel, you are not over the `ListBox` so the only `ScrollViewer` that sees the event is the outer one giving you the behavior you describe.

In the end, the easiest solution is to simply not nest your `ListBox` within a `ScrollViewer` and allow its internal ScrollViewer to handle it. Does that work in your case?

**Comment by darcome** [comment]
Removing the ScrollViewer and applying the height directly to the ListBox worked like a charm!!!

Thank you very much for your help!!!
