### ISSUE TITLE
Derived project from MDIXWindow Example with Close, Maximize e Minimize buttons disabled

### ISSUE THREAD

**Issue by washburnit** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2702]
Hi,
I found this interesting library and I would like to develop my own application using the MDIXWindow example as a kind of "template".
I was able to import all the needed files and install NuGet packages but when I run the application the 3 buttons in the subject are showing but they appear disabled.
I mean, if I click on them nothing happens.
What could I check?
Thank you, regards.

Roberto

**Comment by Keboo** [comment]
That typically happens when the Command the buttons are bound to, is not able to execute (either because its CanExecute method returns false, or it does not find a handler). 
For routed commands the handlers are attached using the `CommandBindings` collection. Can you check and make sure you included the following lines? https://github.com/Keboo/MaterialDesignInXaml.Examples/blob/master/Window/MDIXWindow/MaterialDesignWindow.xaml.cs#L27-L29

**Comment by washburnit** [comment]
Thanks for the prompt reply.
The lines are included since I copied the file "as is" from the source code, I just changed the namespace to make it match to my app's namespace.

**Comment by Keboo** [comment]
@washburnit is the code open source? Would be happy to take a look and see what is going on.

**Comment by washburnit** [comment]
Sure...I'm using Visual Studio 2019 Pro

[Source_Code.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/8764027/Source_Code.zip)

**Comment by washburnit** [comment]
Yes, I didn't notice it !
Now it works, thank you.
Regards,


Roberto

**Comment by Keboo** [comment]
No problem. Happy coding.
