### ISSUE TITLE
Shadow Depth not applied to DrawerHost in both modes

### ISSUE THREAD

**Issue by DarkPro1337** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2804]
### Bug explanation

In 4.4 version there are no problems with `DrawerHost` in `Standard` mode. Version 4.5 has bug when `Modal` mode has a fixed shadow, and `Standard` mode didn't have any shadows. This bug can also be reproduced in nightly build.
On screenshots you can see that there are no matter what `ShadowDepth` is picked. Can it be fixed any way without waiting for a patch?
![MaterialDesignDemo_DvDpHzfYAi](https://user-images.githubusercontent.com/19241806/183125156-0834f00b-3b78-40ad-8d4a-4d9a01ccf775.png)
![image](https://user-images.githubusercontent.com/19241806/183125283-0e1b12a7-0749-4cde-a053-ccae7f9f9001.png)

### Version

4.5.0

**Comment by nicolaihenriksen** [comment]
@DarkPro1337 I think you're experiencing these issues because `ShadowAssist.ShadowDepth` has been replaced with `ElevationAssist.Elevation` in PR #2786.

To avoid breaking existing code, the `ShadowAssist.ShadowDepth` is simply obsoleted for now (to be removed in version 5.0.0), and it has been modified to apply a "corresponding" `ElevationAssist.Elevation` [when applied](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/a26074a7ac7866ad008607350ded86882544183d/MaterialDesignThemes.Wpf/ShadowAssist.cs#L45-L52).

Since these attached properties are not inherited by child elements, setting them via Snoop requires that you set them on the closest `DrawerHost` visual ancestor. If I change `ShadowAssist.ShadowDepth` on the closest `DrawerHost` in Snoop, the corresponding `ElevationAssist.Elevation` is updated accordingly and the UI changes:

![Elevation](https://user-images.githubusercontent.com/19572699/212405550-f61b8f34-4167-4231-a289-e4928cc4dcc6.gif)

---

If you're setting a custom shadow depth in your project, you should probably change it to set the `ElevationAssist.Elevation` instead.

![image](https://user-images.githubusercontent.com/19572699/212402746-2610d2bf-048f-4949-be89-3357879ce6c3.png)
