### ISSUE TITLE
DataGrid, ListView, ListBox scroll into newly added item

### ISSUE THREAD

**Issue by SeynalKim** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2814]
Any change in our  `DataGrid`, `ListView`, and `ListBox` can have the feature to enable or disable the scroll into a newly added item, something like `ScrollIntoView`?

For example;
`ScrollToNewlyAddedItem=True`

Expected behavior:
  - If a new item is added to the list, then scroll to the bottom since it will be added to the last item.
  - If a new item is added to a specific position, then scroll into that position.

**Comment by Keboo** [comment]
Though this is a nice behavior, it is a bit out of scope for this library. The real challenging bit for implementing this is determining when a new item is added (since it is possible to have multiple items added at once). I would also suggest that something like this be built as a behavior rather than an attached property. You can see some examples of doing that [here](https://stackoverflow.com/questions/8827489/scroll-wpf-listbox-to-the-selecteditem-set-in-code-in-a-view-model).

**Comment by SeynalKim** [comment]
I realized this is not that hard using ` DataGrid.ScrollIntoView(item);`. You can also use the `CollectionChanged ` event or `Property`.
