### ISSUE TITLE
ToggleButton Behaviors are always one-way when switching between states

### ISSUE THREAD

**Issue by 721tb** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3070]
### Bug explanation

<materialDesign:PackIcon Margin="5" Kind="{Binding VolumeModel.VolumeState, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}">
                        <b:Interaction.Behaviors>
                            <userBe:HoverShowBehavior TargetElement="{Binding ElementName=VolumeCard}"/>
                        </b:Interaction.Behaviors>
                    </materialDesign:PackIcon>

### Version

Example:4.8.0

**Comment by nicolaihenriksen** [comment]
@721tb I am not sure I fully understand the issue. There is no `ToggleButton` involved in the example code provided. Also, the `HoverShowBehavior` is not a behavior that is part of MDIX to my knowledge, could you provide some info/code for that as well.

Based on the description and the code provided, my guess is that you have a button with an icon which has the kind set from the ViewModel. You then want to use a behavior to update that icon, is that correct? Can your behavior set the `VolumeModel.VolumeState` directly rather than setting the `PackIcon.Kind`? Then you won't need a two way binding. Alternatively you could consider doing this using triggers instead of behaviors?
