### ISSUE TITLE
MaterialDesingThemes icon on OpenDialog not correct since 4.1.0

### ISSUE THREAD

**Issue by DDeAlmeida** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3125]
### Bug explanation

![image](https://user-images.githubusercontent.com/52310650/223486629-8284912a-f975-4566-8765-aa8959bbf3ef.png)
If i try a basic openfile :
![image](https://user-images.githubusercontent.com/52310650/223487148-ed4a3eb3-fffb-48a1-b4b6-db9a5b1d273e.png)

But if i update version to 4.2.1 for example, i have incorrect icon

![image](https://user-images.githubusercontent.com/52310650/223487317-cf60c547-8a60-4fec-8c07-e40374fbd000.png)

![image](https://user-images.githubusercontent.com/52310650/223486787-937c88ed-073c-4f01-a987-28256a100d4d.png)

### Version

4.1.0

**Comment by nicolaihenriksen** [comment]
@DDeAlmeida The icon pack included in `MaterialDesignThemes` is auto-generated and thus potentially breaking in each new release of the library. So for a scenario like this where you are consuming `MaterialDesignExtensions` which in turn consumes `MaterialDesignThemes`, you are best off consuming the version of `MaterialDesignThemes` that `MaterialDesignExtensions` "was compiled against"; otherwise you risk added/removed entries in the [PackIconKind](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/3d1e14d58595131514564e5a278831d99e4b3379/MaterialDesignThemes.Wpf/PackIconKind.cs) causes the consuming library (i.e. `MaterialDesignExtensions`) to point to different icons.
