### ISSUE TITLE
IME Misplaced

### ISSUE THREAD

**Issue by djdjz7** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3147]
### Bug explanation

IME misplaces when textboxes are on DialogHost.

If textboxes are not on a DialogHost, IME behavior is correct, like this:
![image](https://user-images.githubusercontent.com/48580179/227764706-f7721462-18c6-4176-abec-062da9ce9db7.png)

However, if a textbox is placed on a DialogHost, the IME will be misplaced.
![image](https://user-images.githubusercontent.com/48580179/227764658-6c2da279-3338-4608-a950-3fdb5d94c2d2.png)

### Version

4.8.0

**Comment by Red6789** [comment]
Reason：https://social.msdn.microsoft.com/Forums/en-US/3ed11dbe-7b30-46ff-8ce4-4d1096eb5628/cannot-input-chinese-in-the-textbox-of-popup?forum=wpf

**Comment by AndrewKeepCoding** [comment]
This seems to be related to this [issue](https://github.com/dotnet/wpf/issues/4315) on the WPF repo.

**Comment by nicolaihenriksen** [comment]
@AndrewKeepCoding Thank you so much for the help!!

Since you have the repo forked, could I ask you to see if you can repro these memory leaks which I have not been able to reproduce? They both seem to occur on machines with a similar configuration as the IME issue you've just fixed. If you don't have time or don't want to, then that's fine just say so. Thanks.

#3065 and #3282

**Comment by AndrewKeepCoding** [comment]
Hi @nicolaihenriksen!

Sure! Just give me a few days. We are on summer vacation here in Japan, and I'm forced to be away from my laptop for a couple of days...

**Comment by nicolaihenriksen** [comment]
> We are on summer vacation here in Japan

Awesome!! Enjoy your vacation!
