### ISSUE TITLE
Assigning a PackIconKind in code behind returns the wrong enum.

### ISSUE THREAD

**Issue by jrdnwrth** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3159]
### Bug explanation

I've never seen Enums behave like this.  

If you can't reproduce it then just close this and I'll know it was just me.

I am using MaterialDesignThemes 4.8.0.

---- **Decompiling the PackIconKind enum file** ----

This is the icon I want:
![image](https://user-images.githubusercontent.com/8084345/230155405-3b59d58e-589b-480e-8d11-601ac85d74df.png)

This is the icon I get:
![image](https://user-images.githubusercontent.com/8084345/230155799-3b813ef9-41f1-48df-a51f-e10d21487931.png)

My one line of code:
![image](https://user-images.githubusercontent.com/8084345/230156145-8a60bcaf-7f16-4d7a-a4b8-2a9e8d298f7d.png)

I got "Oil".  So what is the integer value of Oil?  4904.  Weird.

It looks like the values of all Enums *changed* right after my line of code.  That can't be possible.  But that's what it looks like:
![image](https://user-images.githubusercontent.com/8084345/230161213-891f5c4c-27eb-4d7d-a614-6994b682ef65.png)

I have no idea how this could occur.   It make me question the reliability of Enums in C# entirely.  I can't even hazard a guess.

I switched back to v4.7.1 and the problem went away.  

### Version

4.8.0

**Comment by nicolaihenriksen** [comment]
@jrdnwrth Relax, you're not going crazy 😆 I can understand the confusion, but I think there is a relatively simple explanation.

The `PackIconKind` is an `enum` that is [auto-generated](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/c6540d6750edf3201544fe52957bec35b05c4085/MaterialDesignThemes.Wpf/PackIconKind.cs#L3-L13) and as such this potentially has breaking changes from release to release.

When you use the `PackIconKind` in code-behind, the ordinal (i.e. `int` value of the enum option) is read at compile time, and thus becomes constant in the produced IL. This gives you a tight coupling to an explicit version of `MaterialDesignThemes` (in your case it seems to be version 4.7.1). If your code then ends up executing using a newer version of `MateerialDesignThemes` (and you accept 4.7.1 as the minimum version), you will run into the issue you see here. Because the ordinal was converted to a constant at compile time, it now points to a different enum option in runtime.

I recently learned (thanks @keboo) that you won't see this issue when you use the `PackIconKind` in XAML, because there a `TypeConverter` will kick in and do the lookup at runtime.

So a work-around is to use a similar approach in your code-behind. Instead of using the enum option directly, you can parse it in runtime to obtain the correct value.

Below is a sample app where I have done exactly what I mentioned above. Using the enum value you also use, I have compiled against a minimum version of 4.7.1, but I have afterwards swapped the 4.8.0 version into the output directory afterwards. As you can see, when I debug the application, the variables using the enum value directly, suffer from the issue you're facing, whereas the ones that parse the value (prefixed "runtime") work as expected.

![image](https://user-images.githubusercontent.com/19572699/230178191-9b0bedaa-4927-4aa6-b414-d36401fd5526.png)

The reason it resolves to `PackIconKind.PackageVariantClosedCheck` is because `PackIconKind.PackageVariantClosedDelivered` is simply an alias for `PackIconKind.PackageVariantClosedCheck` as you can see [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/c6540d6750edf3201544fe52957bec35b05c4085/MaterialDesignThemes.Wpf/PackIconKind.cs#L9412-L9413).

Note that is is of course not production code. You may want to add some error handling in cases where the parsing fails; possibly using `Enum.TryParse()` instead.

**Comment by jrdnwrth** [comment]
Wow.  Thanks for all your effort explaining that to me.  Makes sense.  What a bizarre issue.  I didn't really expect a reply so soon.

**Comment by jrdnwrth** [comment]
Sorry to bother you again.  How do I force it to only use the latest version of the package (4.8)?  I tried deleting the `/bin` directory and `/obj` directory from my project.  I tried `Build -> Clean Solution`.  

I checked the .csproj file.  It is set to this:

    <PackageReference Include="MaterialDesignThemes" Version="4.8.0" />

How do I make it stop compiling version 4.7.1?

**Comment by nicolaihenriksen** [comment]
> How do I make it stop compiling version 4.7.1?

That's interesting; not entirely sure what is happening in your solution.

Simply changing it in the .csproj file like you did, and rebuilding is sufficient in my sample app. In order to "make it fail" I needed to manually drop the wrong version into the output (/bin) and then debug the app without building it first.

With that said, I sometimes see issues in solutions with multiple projects and multiple dependencies. If one package is referenced in one version in one project, and another version in another project then - to my experience - it is the project which compiles first (build order) which "wins" and gets to put the assembly in the /bin folder. Same thing can happen if they are not a direct dependency, but a "dependency of a dependency". So try to go through your solution to check for version mismatches.

If that does not help, you can try using the [Structured Log Viewer](https://msbuildlog.com/) to track down what is happening during the build and investigate why the wrong version is being copied to the /bin folder.

**Comment by nicolaihenriksen** [comment]
> Thanks again!

Glad you managed to identify the root cause and solve the issue!
