### ISSUE TITLE
The "MaterialDesignValidationErrorTemplate" has a bind problem.

### ISSUE THREAD

**Issue by Red6789** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3176]
### Bug explanation

https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ValidationErrorTemplate.xaml
I learned by looking at the source code of the template that there are three lines of code written like this
1. Text="{Binding CurrentItem.ErrorContent, Mode=OneTime}"
2. Text="{Binding CurrentItem.ErrorContent, Mode=OneTime}"
3. Text="{Binding ErrorContent, Mode=OneTime}"
If the Mode is set to OneTime, the ErrorContent will not be updated in real time, and when I change to OneWay, everything is fine, I would like to ask if this is why OneTime is designed this way?

### Version

4.8.0

**Comment by nicolaihenriksen** [comment]
@Red6789 @Keboo It was "recently" changed in this PR: #2955 which focused on perf improvements and leaks.

I believe this was fixed because it was a (potential) leaky binding, but I think I agree with your comments that it effectively kills dynamic updates. I haven't actually tested it, but given that a `OneTime` binding only fetches the bound value once, I would guess it does not work as expected any more.

From the docs:

> Updates the binding target when the application starts or when the data context changes. This type of binding is appropriate if you are using data where either a snapshot of the current state is appropriate to use or the data is truly static. This type of binding is also useful if you want to initialize your target property with some value from a source property and the data context is not known in advance. This is essentially a simpler form of [OneWay](https://learn.microsoft.com/en-us/dotnet/api/system.windows.data.bindingmode?view=windowsdesktop-8.0#system-windows-data-bindingmode-oneway) binding that provides better performance in cases where the source value does not change.

A `OneWay` binding is definitely what we desire here, but if it is a leaky binding, then perhaps something else needs to be done. @Keboo Thoughts?

**Comment by Keboo** [comment]
@Red6789 can you provide a sample of what you are doing to update the errors in real time? The bound property [ErrorContext](https://source.dot.net/#PresentationFramework/System/Windows/Controls/ValidationError.cs,72) is not a bindable property which is the cases that can cause the binding leak (since the Binding has to wrap the property to try and detect changes). It would be helpful to see how you are doing the validation.

**Comment by Keboo** [comment]
@Red6789 thank you so much for the repo. It was very helpful in tracking down the solution. 

I spent most of my [live stream](https://twitch.keboo.dev) tracking down the issue and doing the fix if you are interested in the details.
