### ISSUE TITLE
The text displayed in the MaterialDesign:Flipper widget appears blurry. What could be causing this issue?

### ISSUE THREAD

**Issue by AniFacer** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3220]
### Bug explanation

The text displayed in the MaterialDesign:Flipper widget appears blurry. What could be causing this issue?

### Version

4.9

**Comment by nicolaihenriksen** [comment]
@AniFacer This has always been an issue, and is due to the underlying implementation which is not trivial to fix. For version 5.0, a new `Flipper` implementation was done, and the old `Flipper` was renamed to `FlipperClassic`. So simply updating to version 5.0 should "fix" your issue although you get a slightly different user experience when flipping.

Can you confirm that upgrading fixes your issue?
