### ISSUE TITLE
Rendering (blurry text) issues after upgrading to 4.9 on 4K display

### ISSUE THREAD

**Issue by Awsmolak** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3227]
### Bug explanation

Recently updated app to Release 4.9 from 4.3. Controls within cards and controls displayed within DialogHost are rendering blurry compared to the other parts of my app (.Net Framework). Oddly enough, this seems to only be an issue on my machine that has a 4K display. 

I have noticed a few other issues posted mentioning rendering issues with this latest version. I have not had time to look into the solutions/suggestions in those. Will update here if/when I narrow down the cause further. 

### Version

4.9.0

**Comment by DoctorMarvin21** [comment]
That is important issue. It can be tracked from version 4.8.1. Problem is in drop shadow shadows around cards (and maybe some other elements). When you're adding shadow effect, all content inside of WPF element comes blurry as it's rendered as bitmap:
https://stackoverflow.com/questions/21538296/wpf-dropshadow-on-button-causes-blurry-text

It's a known issue.

**Comment by amine2050** [comment]
Any update on this?

I just updated from 4.8.0 to 5.0.0 and this issue is virtually everywhere where cards with elevation are used. I can see it clearly in the Demo.

![blurry_card](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/20659254/be5ea3d3-f970-4d80-8f6a-148bb35be332)

Not only on High DPI monitors but also on "normal" DPI monitors.

@DoctorMarvin21: Yes it's a known issue in WPF, but there is a simple workaround by separating the background element (generally `Border`) from the content (overlay the content on the `Border`) and applying the shadow effect only on the `Border`.

**Comment by Keboo** [comment]
Yea this was fixed by #3500. The latest previews have the fix. It is probably worth getting a 5.1.0 release out so I can see about doing that in the next week or two.
