### ISSUE TITLE
Ratingbar will have performance problems in Tabcontrol

### ISSUE THREAD

**Issue by Red6789** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3243]
### Bug explanation

Ratingbar will have performance problems in Tabcontrol, and I don't know if it can be optimized.
I provided a demo to show how it happened：
https://github.com/Red6789/AboutMaterialDesign/tree/main/RatingBarPerformance

### Version

4.8.0

**Comment by nicolaihenriksen** [comment]
@Red6789 I apologize for the late response, this must have fallen between chairs.

I looked at your sample, and the reason you're experiencing performance issues in your demo, is because you're using plain `<ItemsControl>` which - by default - does not use virtualization. The `RatingBar` control is inherently a more complex control than a simple `PackIcon` and therefore loading all UI elements into memory will get exponentially worse with the number of items you add.

To "fix" the problem, you can try to change `<ItemsControl>` to `<ListBox>` in your sample and you should see a significant performance boost as the `Listbox` - by default - has virtualization enabled.

With that said, I did notice a number of binding errors within the `RatingBar` template which occur for some of the bindings that travel up the visual tree looking for a parent `RatingBar` (only noticed in your sample, not directly in the demo-app; therefore it was not caught before). This also has a negative impact on the performance, and therefore I think I will look into changing that slightly.
