### ISSUE TITLE
DataGridTextColumn alternate string format on edit

### ISSUE THREAD

**Issue by jbooth88** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3269]
I often have an issue where I would like to have a different string format when the user is editing a DataGrid cell vs. when they are not. Most commonly it's a currency or length field with units that I want to remove when editing, and only display when not editing.  

I guess this could also apply to the text box styles, using the IsFocused property, but I didn't think that far ahead. :)

Normally I have to edit the xaml on each column manually and use a custom implementation of DataGridTemplateColumn (and it works).  However as far as I can see, it requires inputting the same boilerplate code over and over with a different text binding for each column.

This thought came up while I was trying to generate DataGridColumn objects with this behavior in code-behind (which I'm still trying to figure out). I just wanted to bring this idea up because I think it would be quite cool to be able to specify an alternate string format via an attached property (or something similar).

**Comment by nicolaihenriksen** [comment]
@jbooth88 I think I understand what you want to achieve. One issue, off the top of my head, would be the fact that a `DataGridTextColumn` (to my knowledge) renders as a `TextBlock` when not being edited, and thus does not provide easy access to modify a template. So for better control (and to avoid having to explicitly override the default template every time), I think the `DataGridTemplateColumn` is the way to go.

So one approach could be to create a new custom column type (basically a `DataGridTemplateColumn` derived type) which allows you to specify this kind of behavior. You could create such a template column type (i.e. class) in your project, and make it serve your needs for the `StringFormat`. This would keep your XAML relatively clean as you don't have boilerplate code any more inside/around the `DataGrid` element, but rather have explicitly exposed properties on the column types defined inside the `DataGrid.Columns` element, which allows the manipulation you need.

Adding such functionality as a built-in feature of the MDIX library is another story though. For that, I think it would need to be a more "generic" column type which is not restricted to just the `StringFormat`. I can imagine wanting to use leading/trailing icons or other "template-like" stuff. If you come up with a solution which is reasonably generic, it would be great if you would create a PR with it. Then people can provide feedback and it could eventually evolve into something that can be merged into the MDIX library.

**Comment by jbooth88** [comment]
I will experiment to see what I can do in my own project. I would love to contribute but I have near-zero training in github.

My first thought on a solution was to to add an attached property to the datagridcolumn, and add a trigger to the template that changes the text binding based on this property.  Do you think that would work, without the need to create a derived type?

I also find it interesting that the content control has a separate stringformat property. I wonder if the designer of that control had similar thoughts about controlling formatting via triggers.

**Comment by nicolaihenriksen** [comment]
> I would love to contribute but I have near-zero training in github

It is relatively simple. You create a fork of the repo, and then you can simply do a pull request from your fork into the original repo. See this [documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) for inspiration. Let me know if you need assistance.

> I also find it interesting that the content control has a separate stringformat property. I wonder if the designer of that control had similar thoughts about controlling formatting via triggers.

I think it is intended as a "convenience" property which gives you some control when content is rendered as strings. It serves no purpose when the content is not a string as far as I know.

> My first thought on a solution was to to add an attached property to the datagridcolumn, and add a trigger to the template that changes the text binding based on this property. Do you think that would work, without the need to create a derived type?

Interesting idea! I fear that you might struggle to get a hold of that binding in from the trigger in order to manipulate it. The reason I think so is because each of the predefined column types, to my knowledge, are "hard coded" to visualize the content in a certain way. For each type, there are 2 visualizations: "not editing" and "editing". You are provided some control over this via the exposed `DataGridBoundColumn.ElementStyle` and `DataGridBoundColumn.EditingElementStyle`, but I fear that you cannot easily achieve what you want using these. I should say that I have not tested this, so I may be wrong. I guess you could try it out though. Using the `DataGridTextColumn` as an example, you would probably need to modify the `ElementStyle` (i.e. "not editing") by adding a setter for the `Text` property which then uses a binding where the `StringFormat` (from your attached DP?) is then applied - this could be used to display a prefixed "currency symbol" or similar when not editing. You may want to inspect the default WPF templates to see how this binding is originally set up since you effectively want to override it; you should probably retain some of the original "properties" of said binding.

**Comment by jbooth88** [comment]
I think I created a pull request? I hope I didn't push to master by mistake.

I added an override to the GenerateElement() method, that hijacks the binding expression and changes the StringFormat specified by a newly added attached property. Feels like a hack, but it will get my project working at least.

Thanks for the help!

**Comment by nicolaihenriksen** [comment]
> I think I created a pull request? I hope I didn't push to master by mistake.

The repo prevents that so not to worry 😀

Cool, I see the PR. I will take a look at it when I have some more spare time.
