### ISSUE TITLE
what happened to super quick start

### ISSUE THREAD

**Issue by AlizerUncaged** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3307]
### Bug explanation

the page at https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Super-Quick-Start shows chinese characters 

### Version

5-preview

**Comment by MichelMichels** [comment]
Seems like @Keboo removed the page at the end of June. Then it seems like some people re-instated the page with faulty characters? I also see that everyone can edit or delete pages, looks like a permission issue...

@Keboo maybe you should alter the permissions for the wiki?

**Comment by Keboo** [comment]
@MichelMichels yea probably a good call. Originally, I had left it open so that other could help collaborate and when there were problems i just force pushed over the top of them to reset to a clean state. But looking back over recent history I think locking it down to those with push permission is reasonable.

**Comment by Keboo** [comment]
@MichelMichels I also cleaned up the wiki (reset back to a good point) fixing the weird character issue. I also gave you push access :)

**Comment by AlizerUncaged** [comment]
Yay it works now
