### ISSUE TITLE
Expander is not using all available space after expanding inside Grid with ScrollViewer outside

### ISSUE THREAD

**Issue by DrCQ** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3436]
### Bug explanation

I have 3 `Expander` controls inside the `Grid` surrounded by the `ScrollViewer`. The intention is that the third `Expander` should - in the open state - always use all available space. To explain the problem following XAML is used:

```
<Grid>
  <ScrollViewer HorizontalScrollBarVisibility="Disabled" VerticalScrollBarVisibility="Auto">
    <Grid >
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>
        <Expander Grid.Row="0" Header="Fix hight 200" Margin="5">
            <Grid Height="200" Background="Yellow"/>
        </Expander>
        <Expander Grid.Row="1" Header="Fix hight 100" Margin="5">
            <Grid Height="100" Background="Green"/>
        </Expander>
        <Expander Grid.Row="2" Header="Maximal hight" Margin="5" Style="{x:Null}">
            <Grid Background="Blue" MinHeight="400"/>
        </Expander>
    </Grid>
  </ScrollViewer>
</Grid>
```
Setting the `Expander` Style to `Null` shows the proper behavior. Using the MaterialDesign default `Style`shows, that the `Expander` is growing to the `MinHeight` value of the blue `Grid` inside only!

`Window` with `Height` set to 750 perfectly shows the expected behavior between `ScrollViewer` and `Expander`s.

### Version

4.9.0

**Comment by nicolaihenriksen** [comment]
@DrCQ I believe this a simple matter of the `VerticalContentAlignment` of the `Expander` defaults to `Top` in MDIX, rather than `Stretch` which is the default value in the default style. If you explicitly set `VerticalContentAlignment=Stretch` on your `Expander`, I believe you get the expected behavior.

I have added a PR to change the default value because I think it is better to follow the default templates unless there is a specific reason not to; which I don't believe there is in this case.
