### ISSUE TITLE
Show slider value tooltip without having to click first

### ISSUE THREAD

**Issue by vertigo220** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3628]
### Bug explanation

I submitted an [issue to FanControl](https://github.com/Rem0o/FanControl.Releases/issues/2595) which is, per its developer, related to this project. When using the mouse scroll wheel to change a slider, the value tooltip doesn't show unless clicking the slider first. I suppose this could be intended behavior, but it would be nice to have an option to always show the value when changing it without having to click first.

### Version

5.0

**Comment by Keboo** [comment]
Did some investigation into this.

Reproduction steps. In the demo app click on the "tracks" (repeat buttons) above or below the slider thumb. Note that the value changes but the tooltip is not shown until you click on the thumb itself.

It appears that the issue is clicking on the repeat buttons does not move focus to the Slider.

**Comment by corvinsz** [comment]
Some more info on this:

When setting `IsMoveToPointEnabled` to `True` in the style for the Slider, there is additional code executed before the actual `base.OnPreviewMouseLeftButtonDown(e);`. I assume that is the issue with this bug.
For reference see: https://source.dot.net/#PresentationFramework/System/Windows/Controls/Slider.cs,771

Simply setting `IsMoveToPointEnabled` to `False` works, however this would impact the UX since - as the name implies - you can't jump to a value on the track with a single click anymore:
![SliderClickbug](https://github.com/user-attachments/assets/2fadf65e-8ecb-4ab3-87f7-dc6dcfc60ea0)

I created a branch [here](https://github.com/corvinsz/MaterialDesignInXamlToolkit/tree/fix3628SliderToolTipOnClick) if someone wants to fiddle around
