### ISSUE TITLE
PackIcon in button style

### ISSUE THREAD

**Issue by corvinsz** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3658]
### Bug explanation

When setting the Content of a button inside of style to a `PackIcon`, only the last button the style is applied to actually displays the content.
![image](https://github.com/user-attachments/assets/665f1b36-5100-426a-a784-8194a4a912d3)

```xaml
<StackPanel>
  <StackPanel.Resources>
    <Style x:Key="btnFlatDelete"
           BasedOn="{StaticResource {x:Type Button}}"
           TargetType="Button">
      <Setter Property="Height" Value="50"/>
      <Setter Property="Width" Value="50"/>
      <Setter Property="Content" Value="{materialDesign:PackIcon Kind=Bin}"/>
    </Style>
  </StackPanel.Resources>
  <Button Style="{StaticResource btnFlatDelete}" />
  <Button Style="{StaticResource btnFlatDelete}" />
</StackPanel>
```

Background: I tried to define a "delete button"-style in my WPF app. I ended up setting the content for every button individually.

### Version

5.1.0

**Comment by nicolaihenriksen** [comment]
@corvinsz This is because you're defining a shared (by default) resource. The `PackIconExtension` allowing you to declaratively add a `PackIcon` in XAML produces an actual UI element which can only have a single parent (which ends up being the last use of it).

You can mitigate this by explicitly marking your style as non-shared:

```xaml
<Style x:Key="btnFlatDelete"
       BasedOn="{StaticResource {x:Type Button}}"
       TargetType="Button"
       x:Shared="False">
         ...
</Style>
```

You can also extract the `PackIcon` into it's own non-shared resource and statically reference that from the style above. In that case, the `Button` style should be able to be shared

**Comment by corvinsz** [comment]
@nicolaihenriksen I never thought about it this way, but your explanation makes total sense.
Thank you for clarifying!
