### ISSUE TITLE
Invalid DataGridComboBoxColumn.IsEditable = True

### ISSUE THREAD

**Issue by ekicyou** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3683]
### Bug explanation

I will reproduce it with the MaterialDesignDemo.exe app(.NET 8). In the first sample of the DataGrid, for the `Food with long header` column, even though `IsEditable="True"`, when you actually enter data and move to another cell, the entered value disappears.

### Version

5.1.0

**Comment by Keboo** [comment]
This is actually expected behavior. The data grid cells toggle between two states, editable and readonly. When you open a cell in editable mode, and then type into it, if it doesn't match an item in the drop down, it wont actually select a value. Then when you move away from the cell and it goes back to readonly mode. In this case because the editable one does have a value, the value is blanked out.
