### ISSUE TITLE
Weird black sidebars on SmartHints

### ISSUE THREAD

**Issue by LenkaFT** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3700]
### Bug explanation

We've been using materialDesign for wpf for a while now but since the last update those TextBox:

![Hlk9BM2O](https://github.com/user-attachments/assets/2eaed04b-992f-4bfc-8e60-681661fa52fb)

That looks like this in our XML:
```
<TextBox
Grid.Row="1"
Style="{StaticResource MaterialDesignOutlinedTextBox}"
GotFocus="SizeTextBox_GotFocus" LostFocus="TextBox_LostFocus"
PreviewKeyDown="TextBox_PreviewKeyDown"
materialDesign:HintAssist.Hint="{x:Static p:Resources.Height}"
FontSize="25" Height="60" Padding="10" Margin="20"
materialDesign:TextFieldAssist.SuffixText="{Binding Unit, Converter={StaticResource UnitAbbreviation}}"
BorderBrush="{StaticResource PrimaryColorBrush}"
materialDesign:HintAssist.Background="{StaticResource ThirdColorBrush}"
materialDesign:ValidationAssist.Background="{StaticResource ThirdColorBrush}">
    <TextBox.Text>
        <Binding Path="SelectedParameter.Height" UpdateSourceTrigger="Explicit">
            <Binding.ValidationRules>
            <utility:NumericValidationRule/>
            </Binding.ValidationRules>
        </Binding>
    </TextBox.Text>
</TextBox>
```
have those weird black sidebars.

I tried to modify each and everyone props you can access through materialDesign:HintAssist but nothing did the trick.

I also tried to use this to modify the hint :

`
<TextBox.Resources>
    <Style TargetType="{x:Type materialDesign:SmartHint}">
        <Setter Property="Background" Value="red"/>
    </Style>
</TextBox.Resources>
`

It seems I can modify some stuff, mostly props accessible through HintAssist, but setting some other properties doesn't change a thing, margin and padding do nothing for example.

Sorry if that's not a bug but me using a materialStyle i shouldn't associate with hints or something else, but it looks like a bug.

EDIT : Sorry for the badly written issue, it's my first. What you linked seems to be exactly it i'll explore it in my workday thanks !

### Version

4.5

**Comment by LenkaFT** [comment]
Sorry wrong code :

`
<TextBox
Grid.Row="1"
Style="{StaticResource MaterialDesignOutlinedTextBox}"
GotFocus="SizeTextBox_GotFocus" LostFocus="TextBox_LostFocus"
PreviewKeyDown="TextBox_PreviewKeyDown"
materialDesign:HintAssist.Hint="{x:Static p:Resources.Height}"
FontSize="25" Height="60" Padding="10" Margin="20"
materialDesign:TextFieldAssist.SuffixText="{Binding Unit, Converter={StaticResource UnitAbbreviation}}"
BorderBrush="{StaticResource PrimaryColorBrush}"
materialDesign:HintAssist.Background="{StaticResource ThirdColorBrush}"
materialDesign:ValidationAssist.Background="{StaticResource ThirdColorBrush}">
`

**Comment by corvinsz** [comment]
@LenkaFT I'm not sure if I understand your problem correctly because of multiple reasons:
* The screenshot you linked doesn't work for me (FYI: Markdown on GitHub supports copy pasting images)
* I have to change a lot of the code you provided to even get it to compile, since you are referencing static resources like Converters and Brushes, which makes reproducing (and thus tracking down) the bug fairly hard.

Is your problem similar to [this issue (3262)](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/discussions/3262)? If so, @nicolaihenriksen has a good explanation on it ([here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/discussions/3262#discussioncomment-10905148)).
Also have you tried upgrading to the latest version (currently 5.1.0) and see if the bug persists?

FYI: You can edit your comments on GitHub
