### ISSUE TITLE
NumericUpDown up and down buttons not showing

### ISSUE THREAD

**Issue by RandyPJ** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3712]
### Bug explanation

The updown buttons only show up on the last NumericUpDown.

One NumericUpDown:  ![image](https://github.com/user-attachments/assets/33fe8cd8-68e7-4af3-ae5e-f6eba8f5d2d7)
Two NumericUpDowns: ![image](https://github.com/user-attachments/assets/4189e492-91f6-4cce-8002-b8ee78c5b881)
Three: ![image](https://github.com/user-attachments/assets/aa91439b-de6e-4ca8-a0a0-d9fe3e9e4287)

### Version

5.1.0

**Comment by corvinsz** [comment]
@RandyPJ this issue has already been addressed and fixed in #3615 
If you use the latest prerelease NuGet version you can see it working:
![image](https://github.com/user-attachments/assets/0d53a820-ccda-44fe-8b68-db17ead98874)

The fix will be released in the next, 5.2.0 version (I don't recommend using a prerelease version in prod code).
