### ISSUE TITLE
Resource Dictionary problem

### ISSUE THREAD

**Issue by not-word1337** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3718]
### Bug explanation

Hello everyone. I have problem with making styles for buttons and etc. 
usually i'm creating styles like this:
```
<Style x:Key="DefaultTextBox" TargetType="TextBox" BasedOn="{StaticResource MaterialDesignOutlinedTextBox}">
   <Setter Property.../>
</Style>
```
   Always everything was good, but after long time returned to WPF coding, and now when i'm trying to make style as i showed upper, i got this error
 Debuger:
> System.Windows.Markup.XamlParseException: ''Provide value on 'System.Windows.Markup.StaticResourceHolder' threw an exception.' Line number '29' and line position '30'.'

After closing debuger:
![image](https://github.com/user-attachments/assets/6213d1bc-8582-4292-9708-fcf02fc655e2)

Maybe i'm idiot and didn't wrote smthg
**_P.S. this problem i got on 5.1 version, my old project with 4.9 didn't have this problem_**

### Version

5.1

**Comment by corvinsz** [comment]
@not-word1337 the style you provided looks good so far.
Can you double check if you have followed the [Getting started guide](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit?tab=readme-ov-file#getting-started) correctly?
If so, please provide more information about your project, because I'm unable to reproduce your problem.

**Comment by not-word1337** [comment]
WPF (4.7.2 NET)

NuGet package installed
![image](https://github.com/user-attachments/assets/3062efc0-3c9c-442d-a337-a39ebeeb2443)

App.xaml
![image](https://github.com/user-attachments/assets/5fd671f4-e1b3-43b6-9c2d-d30878a9386d)

Dictionary
![image](https://github.com/user-attachments/assets/51c64a80-c18c-4409-942f-f4efeccac1a1)

Window
![image](https://github.com/user-attachments/assets/306cffbd-fa12-441e-a611-bea5d0ad086e)

**Comment by corvinsz** [comment]
@not-word1337 I assume the problem is that you are adding your own/custom ResourceDictionary (which uses MDIX styles) before the MDIX ResourceDictionary. The order of operations matter:
```xaml
...
<Application.Resources>
    <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
            <materialDesign:BundledTheme BaseTheme="Inherit"
                                         PrimaryColor="DeepPurple"
                                         SecondaryColor="Lime" />
            <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesign3.Defaults.xaml" />
            <!--define your additional ResourceDictionaries here-->
        </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
</Application.Resources>
...
```

Also FYI:
Most of the time styles are referenced via a `StaticResource`, only resources like `Brushes`, which can change at runtime should be referenced via a `DynamicResource`.
Unless you need the dynamic loading of resources, `StaticResource` should probably be "the default" since it's resolved and assigned during the loading of the XAML, rather than at runtime (thus making `StaticResource` more performant).

**Comment by not-word1337** [comment]
omfg 
i forgot that order make sense xd
ty 4 much n ty 4 advise

sorry for one more question
how can i change this white background 
![image](https://github.com/user-attachments/assets/6b0a5251-d49e-492a-a6fd-a5e96424c567)

i mean i have hintassist.background set to "#141414"
but still have this white background behind i already have, as i understood this is something new from 5.x version, but can't find how to change it

**Comment by corvinsz** [comment]
@not-word1337 if I recall correctly this issue has been addressed recently.
Beside that, you don't want to straight up hardcode colors (for example in line 11, the `<Grid Background="#141414">`) in your app, since the MDIX library isn't aware of those colors and can't adjust them depending on the theme (light/dark mode).

If you want your app to be in dark mode, consider setting the `BaseTheme="Dark"` in your app.xaml like so:
```xaml
<materialDesign:BundledTheme BaseTheme="Dark"
                             PrimaryColor="DeepPurple"
                             SecondaryColor="Lime" />
```

You can also use `BaseTheme="Inherit"` to use the current Windows theme.

**Comment by not-word1337** [comment]
@corvinsz i mean that i just want to remove that not settings to light or dark color
we have `HintAssist.Background` and we can set it to any color, usually in 4.9 i setted in to "Transperent" or color like window's background. But in 5.x i have this white background, when i set `HintAssist.Background` to Transperent i still have this white unknown background
