### ISSUE TITLE
Window Title Bar Color

### ISSUE THREAD

**Issue by NormskiJJO** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3719]
Can the there be a feature added to allow Window Title Bar Color reflect the same color as the primary color?

**Comment by corvinsz** [comment]
@NormskiJJO customizing the Window's Titlebar is not as trivial as one would think, since it's considered the non-client area of a window.

Since .NET Framework 4.5 Microsoft provides a somewhat easy way to modify what is called the [WindowChrome](https://learn.microsoft.com/en-us/dotnet/api/system.windows.shell.windowchrome?view=windowsdesktop-9.0&redirectedfrom=MSDN).
I have created a repo ([CustomWindowChromeExample](https://github.com/corvinsz/CustomWindowChromeExample)) which leverages that API and creates a custom window chrome. Note that this was more of a PoC and may not be production ready.

**Comment by Keboo** [comment]
This is something that has been requested before. I think the simplest option is to also include either [MahApps](https://mahapps.com/) or its underlying [ControlzEx](https://github.com/ControlzEx/ControlzEx) library to accomplish this. There is a MahApps sample in this repo as well.

For now, there are no plans to include custom window chrome directly in this library.
