### ISSUE TITLE
When I scroll in the Card page throw a COMException

### ISSUE THREAD

**Issue by zhaotianff** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3724]
### Bug explanation

System.Runtime.InteropServices.COMException:“UCEERR_RENDERTHREADFAILURE (异常来自 HRESULT:0x88980406)”

![demo](https://github.com/user-attachments/assets/709d5b8c-18dd-40b2-8748-a0b7b9d63ba5)

### Version

master

**Comment by corvinsz** [comment]
@zhaotianff it seems like the app is crashing as soon as the `Flipper` (or `FlipperClassic`) is being rendered.
Since I can't reproduce this bug, can you by chance comment out, first the `FlipperClassic`, and then the `Flipper` to see which one of them is causing the problem?
If I recall correctly the `Flipper` and `FlipperClassic` work quite differently behind the scenes.

I created a branch [here](https://github.com/corvinsz/MaterialDesignInXamlToolkit/tree/fix3724FlippersCommentedOut):
* [first change](https://github.com/corvinsz/MaterialDesignInXamlToolkit/blob/266409a502be1964d597b8ab2e9b0ac2fe94a6ac/src/MainDemo.Wpf/Cards.xaml#L344)
* [second change](https://github.com/corvinsz/MaterialDesignInXamlToolkit/blob/266409a502be1964d597b8ab2e9b0ac2fe94a6ac/src/MainDemo.Wpf/Cards.xaml#L517)

**Comment by zhaotianff** [comment]
Thank you for your reply,looks like a problem with my computer environment.

I found this document:
[https://learn.microsoft.com/en-us/troubleshoot/developer/dotnet/framework/general/wpf-render-thread-failures](https://learn.microsoft.com/en-us/troubleshoot/developer/dotnet/framework/general/wpf-render-thread-failures)

maybe video hardware or driver problems.
