### ISSUE TITLE
Binding to IsAllItems3Selected property does not work in Grids user control

### ISSUE THREAD

**Issue by pavl0v** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#466]
Binding to IsAllItems3Selected property does not work in Grids user control. It is impossible to check/uncheck all items in DataGrid ("Custom Columns" section, demo). [Update]: This behaviour does NOT appear in the case of Grids control is a first item in the ListBox ("DemoItemsListBox") of LeftDrawerContent.

**Comment by baikimi** [comment]
edit this method like this 
   private static void SelectAll(bool select, IEnumerable<SelectableViewModel> models)
        {
            foreach (var model in models)
            {
                model.IsSelected = select;
            }
             Items1 = null;
            Items1 = models;
        }

**Comment by Scantheus** [comment]
In order to get this to work I had to add the DataContextSpy class (https://www.codeproject.com/Articles/27432/Artificial-Inheritance-Contexts-in-WPF).

In Grids.xaml.cs:  add DataContextSpy class.

In Grids.xaml :

Add... 
xmlns:local="clr-namespace:MaterialDesignColors.WpfExample"

Add....
<DataGrid.Resources>
       <local:DataContextSpy x:Key="spy" />
</DataGrid.Resources>

Replace...
DataContext="{Binding RelativeSource={RelativeSource AncestorType={x:Type DataGrid}}, Path=DataContext}"

With...
DataContext="{Binding Source={StaticResource spy}, Path=DataContext}"

**Comment by MJNSoftware** [comment]
Thanks @Scantheus that was a big help to us. 
The demo code follows the sample here 
https://code.msdn.microsoft.com/windowsdesktop/Binding-of-DataGrid-column-73f80f68 
I presume that demo will have worked a some point, any idea why this has stopped working?

**Comment by Scantheus** [comment]
I found an alternate solution that is closer to original code. Use HeaderTemplate instead of Header.

<DataGridCheckBoxColumn.HeaderTemplate>

   <DataTemplate>
       <Border Background="Transparent" Padding="6 0 6 0"  HorizontalAlignment="Center">
           <CheckBox HorizontalAlignment="Center"
               DataContext="{Binding RelativeSource={RelativeSource AncestorType={x:Type DataGrid}},              Path=DataContext}"
                IsChecked="{Binding IsAllItems3Selected}" />
      </Border>
   </DataTemplate>
</DataGridCheckBoxColumn.HeaderTemplate>
