### ISSUE TITLE
Drawerhost/DialogHost overlay custom property for opacity and color

### ISSUE THREAD

**Issue by StealthRT** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#568]
I would like you to revisit the overlay for the flyout issue that you **do** add this as a property @ButchersBoy . I would like to be able to change the overlay color and also its opacity. I feel this would be a nice added feature and much needed depending on the users design habits.

If its also possible, it would be nice to also include the fade in/out time it takes if someone wants an instant background to appear or slowly fade in/out/etc.

**Comment by varunvasisht84** [comment]
@ButchersBoy : The partial fix of this issue is done under https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/pull/779/commits/d8aeb6373d97bfe3429b068af702ab257bf3bc44 . However I could not create the new pull request. It got merged under my previous open PR (#779). Just making sure it is not lost.

**Comment by MichelMichels** [comment]
Is there any work left on this feature request?

**Comment by Keboo** [comment]
Looks like it should have been resolved with #1364
