### ISSUE TITLE
Expander Header: StringFormat not formatting string

### ISSUE THREAD

**Issue by MysticAppDevelopment** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#722]
I'm binding a normal string to the Header of an Expander and trying to format the string using StringFormat. The binding works, but is not being formatted. It's not that it's being formatted incorrectly, it's not being formatted at all.

**Comment by quicoli** [comment]
Hi, that is not a problem with MaterialDesignInXaml.

That happens because of the structure of Header in WPF. It is not a string.
See:

https://msdn.microsoft.com/en-us/library/system.windows.controls.headeredcontentcontrol.header(v=vs.110).aspx

To accomplish what you need, I suggest you something like:


   1. <Expander Name="ExpanderControl"
   2.   HorizontalAlignment="Left" Background="LavenderBlush"
   3.   ExpandDirection="Down"  IsExpanded="False" Width="250"
   4.           FontSize="20" FontWeight="Bold" Foreground="Green" >
   5.     *<Expander.Header>   *
   6. *            <TextBlock Margin="20,0,0,0" Text="{Binding
   YourViewModelProperty, StringFormat={}{0:your_formatting}}"  </TextBlock>
   *
   7. *      </Expander.Header>*
   8.
   9.     <TextBlock TextWrapping="Wrap" FontSize="14" FontWeight="Light"
   Foreground="Black">
   10.
           This is an Expander control. Within this control, all
contents will be wrapped.
   11.
           At run-time, you may expand or collapse this control. Type
more text here to be typed.
   12.         Jump around and hype.
   13.     </TextBlock>
   14. </Expander>




2017-05-31 11:55 GMT-03:00 MysticAppDevelopment <notifications@github.com>:

**Comment by ButchersBoy** [comment]
@MysticAppDevelopment   Are you sure ```HeaderStringFormat``` is not what you want?
