### ISSUE TITLE
Produce demo with FULL catalog [Enhancement]

### ISSUE THREAD

**Issue by wongjiahau** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#756]
- As one of the user of this library, I feel like it is very important to catalog all the styles in the demo, what I mean is that the style should be easily copyable from the demo (because looking through codes in GitHub) is actually very frustrating 
- Another problem is some styles is not mentioned in the Demo, so user might not noticed it, for example, some transition effects are not included in the MainDemo at all 
- Therefore, I hereby request help for producing a demo with full catalog (of course I will be contributing to it as well)

**Comment by ButchersBoy** [comment]
Hey yes...

I have thought about this, and I think something that could scan ANY XAML library and lists styles and locations of those styles would be useful, and a good start...

**Comment by wongjiahau** [comment]
To achieve this, I think we can use the XamlWriter class. 
[(https://msdn.microsoft.com/en-us/library/system.windows.markup.xamlwriter(v=vs.110).aspx )]

**Comment by wongjiahau** [comment]
And also [XamlReader.Parse](https://msdn.microsoft.com/en-us/library/cc663033(v=vs.110).aspx)

**Comment by Keboo** [comment]
The big [drawback](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/serialization-limitations-of-xamlwriter-save) to using the XamlWriter class is that you get the run-time representation of the object. This can get rather large since you can easily end up with a huge amount of XAML that you did not expect.
Something simple like this:
```XAML
<Button Style="{StaticResource MaterialDesignFlatButton}" />
```
Ends up writing out all of the elements in the style in addition to the button. If someone is expecting to simply Copy and Paste this XAML it could quickly get out of hand.

Since I think the idea result is to display the original logical tree. I am thinking that a solution that parses the BAML and displays that information. Though this is not completely trivial itself. Sure we can go through and load the BAML, but this comes with its own challenges. 

Something along the lines of this:
```C#
var assembly = Assembly.GetEntryAssembly();
var resourceStream = assembly.GetManifestResourceStream(assembly.GetName().Name + ".g.resources");
if (resourceStream == null) return;
var resourceReader = new ResourceReader(resourceStream);
foreach (var dictionaryEntry in resourceReader.OfType<DictionaryEntry>()
    .Where(de => de.Key is string name &&
                    name.EndsWith(".baml", StringComparison.InvariantCultureIgnoreCase) && de.Value is Stream))
{
    Baml2006Reader reader = new Baml2006Reader((Stream)dictionaryEntry.Value);
    while (reader.Read())
    {
        //TODO?
    }
}
```

Loading Xaml from the currently executing assembly can have problems since it will load it into the running application. Loading the Xaml this way it will try to load into the running application which causes error due to duplication. This also does not fully solve the problem of linking the UI element back to its corresponding Xaml, but that seems like something that should be solvable.

As an alternative we could attempt to process the Baml as part of the compile process. I have some experience building [Fody weavers](https://github.com/Fody/Fody). This would be similar to how [GitLink](https://github.com/GitTools/GitLink) works. I would envision doing something like:
1. Iterate over all of the Baml resources in the assembly
2. Convert the Baml to Xaml (we can do it here since the baml is not part of the running application)
3. For each element add an attached property that contains a unique id. Save the elements Xaml as an xaml resource.
4. Save the modified Xaml as Baml as replace the original in the assembly (never done this but I suspect it should be simple-ish). I am also not sure if the new VS Xaml tools will play nice with this or not.
5. Now given any element in our demo allocation we can simply check it for the attached property. If it exists we can use the unique id on it to look up the xaml resource to display.

Thoughts?

The other question is how to surface this in the demo application. I do like the idea of using the AvalonEdit control to get nice syntax highlighting, though I am not sure how/where that should be displayed in the UI.

**Comment by wongjiahau** [comment]
@Keboo Yes, that is a big drawback, so currently, I am thinking of doing it the other way round. That is to write the XAML code in CS, then load it into the UI using XamlReader. I'll show it to you the demo soon.

**Comment by ButchersBoy** [comment]
Hi guys, 

Another thought, just parsing the XAML outside of the demo, and spitting out some HTML is worth considering, bedside then we can just add a list to the wiki/website somewhere.

Let's not forget that XAML is just XML so possibly just xpath or linq2xml would get that done.

**Comment by wongjiahau** [comment]
![image](https://user-images.githubusercontent.com/23183656/28721356-9f43ced2-73e2-11e7-9bd4-974d0c7875ab.png)

![image](https://user-images.githubusercontent.com/23183656/28721388-ba016a4a-73e2-11e7-8ec6-cc38e18e9fd7.png)


This is what I've done so far. 
The only drawback is there are no syntax checking for the XAML, since they are typed in CS file, however, this is not really an issue, because if there are error in the XAML code, XamlParseException will be thrown at run time, so the correctness of the XAML can be guaranteed. 
Please refer to [this repository](https://github.com/wongjiahau/Displaying-XAML) for the full code.

**Comment by wongjiahau** [comment]
Second attempt to solve this problem : 

### Output 
![image](https://user-images.githubusercontent.com/23183656/28752202-633d468c-754c-11e7-994a-d966370e4cdc.png)

### Xaml Code
![image](https://user-images.githubusercontent.com/23183656/28752152-5bcff9a4-754b-11e7-96f7-d84c60d46153.png)

### Code behind 
![image](https://user-images.githubusercontent.com/23183656/28752190-1ac5c438-754c-11e7-983b-515b8ce6e433.png)

### How to do it ? 
1. If you want to display the Xaml of a control, just embed it within the XamlDisplayer (make sure the XamlDisplayer is given a name(any name will do)).
2. Load the Xaml file in the code behind, then call the XamlDisplayer.DisplayXamlCode method. 
3. That's all. 

### Advantage 
1. This method can be surfaced easily in the MainDemo.wpf  without modifying much base code. 

### Issues 
1. How are we going to load the xaml file? Perhaps using GitLink as suggested by @Keboo 


Thank you for reading this. I hope you'll review it. 




Please refer to [this repository](https://github.com/wongjiahau/Displaying-XAML) for the full code.

**Comment by Keboo** [comment]
Hi @wongjiahau this looks very interesting. When I have a little more time I will look over it more closely.

**Comment by wongjiahau** [comment]
Third attempt to solve this problem : 

### Output 
![demo](https://user-images.githubusercontent.com/23183656/28815466-0da11b66-76d4-11e7-8b7a-a0771d98d55a.gif)

### Xaml Code
![image](https://user-images.githubusercontent.com/23183656/28815326-94f7bc38-76d3-11e7-90ea-7a41f2924885.png)

### Code behind 
![image](https://user-images.githubusercontent.com/23183656/28815602-7c80b302-76d4-11e7-8d93-b1ac197c44f5.png)


### How to do it ? (Now it's even easier!)
1. Just embed the controls that you want its XAML to be displayed within a single XamlDisplayerPanel (remember to name the XamlDisplayerPanel).
2. Load the Xaml file from Github in the code behind, then call the XamlDisplayerPanel.Initialize method. 
3. That's all. 

### Advantage 
1. This method can be surfaced easily in the MainDemo.wpf  without modifying much base code. 

Thank you for reading this. I hope you'll review it. 
Please refer to [this repository](https://github.com/wongjiahau/Displaying-XAML) for the full code of XamlDisplayerPanel.

**Comment by Keboo** [comment]
Hi @wongjiahau 
I am trying to run the code, but it appears that one of the references in CodeDisplayer is a local file.
```XML
<Reference Include="XamlStyler.Core">
  <HintPath>..\..\..\XamlStyler\XamlStyler.Core\bin\Release\XamlStyler.Core.dll</HintPath>
</Reference>
```

Is this something that can be checked in?

**Comment by wongjiahau** [comment]
@Keboo Sorry for the problem, I had already fixed that by including the .dll in the repository. 

![image](https://user-images.githubusercontent.com/23183656/28855224-31c8e696-776e-11e7-8d85-5f4b3ea449e3.png)

![image](https://user-images.githubusercontent.com/23183656/28855321-ba5c838c-776e-11e7-8ae5-ceda1c45fd92.png)

**Comment by AmitBhatnagar24** [comment]
I just tried this out, (via download link in gitter) and it is awesome. 

This makes the demo app 100x more useful and saves me loads of time.

Great work!

**Comment by wongjiahau** [comment]
@AmitBhatnagar24 Thanks :) 
@ButchersBoy  I hope you will include this feature in the next release, as this will greatly reduces the gulf of execution. Most of the users (for example myself), whenever I want to use a type of control, I can picture it in my mind, but I can't really remember its code, therefore I'll need the catalog to easily get the code I want.

**Comment by varunvasisht84** [comment]
Hello @wongjiahau ,
Cool stuff. I'll try it with one of my application written in wpf.

varun

**Comment by AmitBhatnagar24** [comment]
@wongjiahau This doesn't seem to work anymore - crashes upon launch. I'm suspecting its failing when trying to pull the latest demo code source from GitHub?

**Comment by wongjiahau** [comment]
@AmitBhatnagar24 Yes, because I've updated the source code yesterday, try download the latest version [here](https://www.dropbox.com/s/u0ksfhdg0fkv8vr/MaterialDesignDemo%28withCodes%29.exe?dl=0)

**Comment by Keboo** [comment]
This has been implemented in the demo app.
