### ISSUE TITLE
Adding the MaterialDesignThemes NuGet package causes build warnings

### ISSUE THREAD

**Issue by PetarKirov** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#778]
Steps to reproduce:
1. Clone https://github.com/ZombineDev/WpfApp1 (for this example I will put it on my `D:\` drive)
2. Open `WpfApp1/WpfApp1.sln` in Visual Studio
3. Restore NuGet packages (e.g. from Tools -> NuGet Package Manager -> Manage NuGet Packages for Solution... -> Click on the Restore button)
4. Raise build output verbosity from Tools -> Options -> Project and Solutions -> Build and Run -> set "MSBuild project build [output]/[log file] verbosity" to "Diagnostic"
5. Rebuild the project
6. Open the "Output" window.
7. Search for "There was a conflict between"

The message that I get is:
```
1>  There was a conflict between "MaterialDesignColors, Version=1.1.3.0, Culture=neutral, PublicKeyToken=null" and "MaterialDesignColors, Version=2.3.0.823, Culture=neutral, PublicKeyToken=null". (TaskId:20)
1>      "MaterialDesignColors, Version=1.1.3.0, Culture=neutral, PublicKeyToken=null" was chosen because it was primary and "MaterialDesignColors, Version=2.3.0.823, Culture=neutral, PublicKeyToken=null" was not. (TaskId:20)
1>      References which depend on "MaterialDesignColors, Version=1.1.3.0, Culture=neutral, PublicKeyToken=null" [D:\WpfApp1\packages\MaterialDesignColors.1.1.3\lib\net45\MaterialDesignColors.dll]. (TaskId:20)
1>          D:\WpfApp1\packages\MaterialDesignColors.1.1.3\lib\net45\MaterialDesignColors.dll (TaskId:20)
1>            Project file item includes which caused reference "D:\WpfApp1\packages\MaterialDesignColors.1.1.3\lib\net45\MaterialDesignColors.dll". (TaskId:20)
1>              MaterialDesignColors, Version=1.1.3.0, Culture=neutral, processorArchitecture=MSIL (TaskId:20)
1>      References which depend on "MaterialDesignColors, Version=2.3.0.823, Culture=neutral, PublicKeyToken=null" []. (TaskId:20)
1>          D:\WpfApp1\packages\MaterialDesignThemes.2.3.0.823\lib\net45\MaterialDesignThemes.Wpf.dll (TaskId:20)
1>            Project file item includes which caused reference "D:\WpfApp1\packages\MaterialDesignThemes.2.3.0.823\lib\net45\MaterialDesignThemes.Wpf.dll". (TaskId:20)
```

**Comment by Keboo** [comment]
I also see this behavior (though worth pointing out it is not actually a build warning, just diagnostic output).  If you look at the manifest for the MaterialDesignThemes.Wpf.dll you will see:
```
.assembly extern MaterialDesignColors
{
  .ver 2:3:0:823
}
```

I suspect what is happening is the [AppVeyor assembly patching](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/appveyor.yml#L9-L14) is applying to the colors nuget as well (I assume this must be manually done since I don't see it in the appveyor script) and then compiling the colors library based on that.

The simplest fix is to make this library reference the colors lib via the nuget reference. Perhaps add a conditional project reference for Debug builds if to make updating the two together easier.

**Comment by ZombineDev** [comment]
> though worth pointing out it is not actually a build warning, just diagnostic output

I actually got a very similar build **warning** in a larger project, but I was not able to replicate it in a smaller project. I think it was MSB3247.

**Comment by Keboo** [comment]
This issue does not appear to be happening with the latest 4.2.1 release
