### ISSUE TITLE
Improve DialogHost.Show behavior

### ISSUE THREAD

**Issue by uPloraX** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#792]
I'm currently using the `DialogHost.Show()` method in my ViewModels.
Aside from using a static call in my ViewModels isn't that good, the current behavior could improve in my opinion.

It's ugly to wrap every `.Show()` within a try catch block, because I can't check if the DialogHost is open.
I could think of these possibilities:

- Add a queue like the Snackbar has it
- Force close the previous dialog (by overload)
- Ignore the next to be shown dialog if one is currently open (by overload)
- Add a static CheckOpen method with optional dialog identifier as overload

**Comment by Keboo** [comment]
Though there is certainly room to improve the DialogHost API, I would suggestion using dependency injection to solve this particular problem. 
Rather than litter my view models with static calls to `DialogHost.Show()`, I instead have an `IDialogService` that is passed to the view models. Because all of the dialog interaction flows through this class it can easily track things like which dialog hosts are open.
