### ISSUE TITLE
Close dialog from DialogHost using an attached property

### ISSUE THREAD

**Issue by Tyrrrz** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#808]
Currently the most viable strategy to close dialogs from inside is to use the DialogHost.CloseCommand. However, it's not that rare that a button may need to execute a command of its own and then also close the dialog. In that case, an event handler has to be added. It would be convenient if there was an attached property such as `DialogHost.ClosesDialogOnClick` that makes the button close the dialog on click.

**Comment by Keboo** [comment]
Though this is certainly possible, I am not sure if it is the correct design. The big issue is async event handlers. 
Because command execute methods are considered top level event handlers, it is perfectly valid for them to be declared as `async void`. This means that it is impossible to know when the command is "done" executing. 

Though I do agree with you, closing the dialogs that have been opened at times feels very kludgy. I have tended to favor calling [DialogHost.ShowDialog and using the Session object](https://github.com/Keboo/MaterialDesignInXaml.Examples/blob/master/DialogHost/DialogHost.Example/MainWindowViewModel.cs#L22-L29) to give me control over when the dialog should close. So far this is the cleanest solution I have come up with.

**Comment by Keboo** [comment]
Closing for now as this gets problematic especially with async command handlers. It is typically best of the logic for this lives within each application and not in the library.
