### ISSUE TITLE
File and folder picker controls

### ISSUE THREAD

**Issue by Tyrrrz** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#809]
It would be nice to have a file/folder picker control, similar to the DatePicker - a textbox and a button that shows a popup to help you locate the file.

**Comment by wongjiahau** [comment]
But the official guideline does not provide a design guide for FileDialogs.

**Comment by Tyrrrz** [comment]
Most likely because mobile devices have their own file picker, provided by the OS instead of the app.

**Comment by mgnslndh** [comment]
I'd like a file/folder picker "view" similar to this:

![file-manager-material-design](https://user-images.githubusercontent.com/1139118/31100255-018ac20c-a7c9-11e7-8ab2-b847bb37e283.jpg)

The pic above is file manager but I'd like something similar to pick files/folders. Ability show meta data in order to help pick the right file.

Might be too big for MDT and could possibly be a separate library with styles for both MDT and MahApps.

**Comment by spiegelp** [comment]
@Tyrrrz I might need such kind of controls in the near future, so I started them [here](https://github.com/spiegelp/MaterialDesignExtensions).

**Comment by Keboo** [comment]
As this is covered by the Material Design Extensions library, i don't think this is likely to make it into this library directly
