### ISSUE TITLE
FocusManager.FocusedElement on Textbox with hint not working

### ISSUE THREAD

**Issue by Symbai** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#850]
I have a transitioner with two pages. On the second page i have a textbox with a hint. Setting a focus on it via FocusManager.FocusedElement="{Binding ElementName=Mytextboxname}" in XAML kinda sets the focus on it when I switch to the  second page as I can see the caret, but makes it impossible to type without clicking on it first.

**Comment by Keboo** [comment]
@Symbai the issue here is the subtle differences between logical and keyboard focus (full docs [here](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/focus-overview)).

What you will want to do is call `Keyboard.Focus` ([docs](https://docs.microsoft.com/en-us/dotnet/api/system.windows.input.keyboard.focus?view=netframework-4.7.1#System_Windows_Input_Keyboard_Focus_System_Windows_IInputElement_)). On the element. There is no direct way to do this with XAML but you can do it with an attached property, or a behavior.

**Comment by Symbai** [comment]
FocusElement sets a focus but pressing a key will not do anything
Keyboard.Focus does nothing at all to the textbox (placing it in the Transitioner selectionchanged event)
