### ISSUE TITLE
Missing possibility to adjust the Padding in the expander header

### ISSUE THREAD

**Issue by Revsol** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#855]
It would be great to have a easy possibility to adjust the padding from the header of an expander. Currently the padding comes from border of the ToggleButton and is 24,12,24,12.

**Comment by jespersh** [comment]
A ExpanderAssist wouldn't be the worst to create a slimmer expander

**Comment by Keboo** [comment]
I am not opposed to the ExpanderAssist idea. However, it is important to note that the the padding does changes from `24,12,24,12` to `12,24,12,24` [based upon the ExpanderDirection](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Expander.xaml#L317-L347). This does pose a bit of a problem, since if you set the default value for ExpanderAssist property in these triggers, you prevent the users of the expander from overriding it. Though not common, we do need to handle the ExpandDirection changing at run-time, with potentially different Paddings for each `ExpandDirection`.

I would propose the following: 

1. Create 4 attached properties in a new ExpanderAssist class (`LeftHeaderPadding`, `RightHeaderPadding`, etc). These properties should be [inheritable](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/property-value-inheritance#making-a-custom-property-inheritable).
2. Set the default values for each of these properties in the [MaterialDesignExpander style](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Expander.xaml#L221)
3. Replace the hard coded padding values in each of the header button styles with the appropriate attached property.
