### ISSUE TITLE
Weird animation / Slow perfomance with ComboBox

### ISSUE THREAD

**Issue by kruherson1337** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#928]
I am getting weird animation and slow performance when using ComboBox. 

Following code snippet is ComboBox declaration in FXML. I am using WPF.

` <ComboBox x:Name="comboBoxPacient" materialDesign:HintAssist.Hint="Pacient" IsEditable="True" Style="{StaticResource MaterialDesignFloatingHintComboBox}" ... />
`

When loading data I am setting `ItemsSource` as follows. I am loading ~**2000 items**.

`comboBoxPacient.ItemsSource = pacients;`

But when trying to select item, it takes couple of seconds to load and weird animations appears. After first time loading it works fine. Can I preload it somehow?

I am providing .GIF to show it in action. 

![issue](https://user-images.githubusercontent.com/22047383/38168373-478060be-354a-11e8-8823-9e46f98349e0.gif)

**Comment by kruherson1337** [comment]
I have fix this issues with following solutions, found on stackoverflow.

I have added this to my ComboBox declaration in FXML

```
<ComboBox.ItemsPanel>
    <ItemsPanelTemplate>
        <VirtualizingStackPanel />
    </ItemsPanelTemplate>
</ComboBox.ItemsPanel>
```

after applying this code it works fine!

more [HERE](https://stackoverflow.com/a/8834289/3692170)

**Comment by Keboo** [comment]
I believe this is the default behavior for ComboBoxes since even the [default WPF ComboBox](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/combobox-styles-and-templates) does not use virtualization by default
There are also a [couple examples in the demo application](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/TextFields.xaml#L142-L213) showing additional examples of using the VirtualizingStackPanel.

**Comment by MichelMichels** [comment]
Closed due to inactivity
