### ISSUE TITLE
The "BuildXamlDictionaryTask" task failed unexpectedly. 

### ISSUE THREAD

**Issue by Ajepetobi01** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#929]
Trying to run the demo app and i keep getting this error

The "BuildXamlDictionaryTask" task failed unexpectedly. 
System.TypeLoadException: Could not load type 'System.ValueTuple`2' from assembly 'mscorlib, Version=4.0.0.0		

![materialdesignerror](https://user-images.githubusercontent.com/8195292/38250575-0e54ba84-3747-11e8-8637-96ca83c72936.PNG)

Please i need help!

**Comment by Ajepetobi01** [comment]
@Keboo I use VS2017. Don't know why i am getting this error!

**Comment by Keboo** [comment]
@Ajepetobi01 I just published a new build that removes the .NET 4.7 dependency (which is what I suspect is the root cause of this). Can you try updating to the [latest preview nuget 1.0.10-ci45](https://www.nuget.org/packages/ShowMeTheXAML/1.0.10-ci45) and let me know if that resolves the issue?

If you are not familiar with [packet](https://fsprojects.github.io/Paket/) (the package manager that is being used) you will need to edit the [packet.dependencies](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/paket.dependencies) file to be:
```
nuget ShowMeTheXAML ~> 1.0.10-ci45
nuget ShowMeTheXAML.AvalonEdit ~> 1.0.10-ci45
nuget ShowMeTheXAML.MSBuild ~> 1.0.10-ci45
```
You may also need to [run the install command](https://fsprojects.github.io/Paket/getting-started.html#Installing-dependencies) to make sure it grabs the latest packages.

**Comment by CrestApps** [comment]
I had the same problem. I did the following to solve it.

I changed the .net version on all the projects to 4.6.2. Then I installed the `ShowMeTheXAML` as described above and it worked for me. I am not sure if I did more steps that what is required, but it is working for me now.

**Comment by Keboo** [comment]
@CrestApps thanks for testing that. I will do a full release package of `ShowMeTheXAML` and get a PR in for it.

**Comment by baikimi** [comment]
same problem can't solve it what should i do

**Comment by Keboo** [comment]
@CenturySpine did you also run the [packet install command](https://fsprojects.github.io/Paket/getting-started.html#Installing-dependencies) from the root of the repository?
```
.paket/paket.exe install
```

**Comment by CenturySpine** [comment]
ok that worked with the packet command. Thanks !!

**Comment by Keboo** [comment]
@CenturySpine perfect, I will get a PR submitted for it.

**Comment by liujunhome** [comment]
This bug has been resolved ,new bug have emerged,Unable to resolve Resource，But building is success,
 Please i need help!
![error](https://user-images.githubusercontent.com/24474771/41653986-7e491ca8-74ba-11e8-82c1-e2afb6040682.jpg)
