### ISSUE TITLE
Different Brushes (Intention?)

### ISSUE THREAD

**Issue by Symxn** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#954]
Hello,

Why is the PrimaryBrush different to the SecondaryBrush?
This is only since the last update.

![color bug](https://user-images.githubusercontent.com/37656980/40235434-8b57eb10-5aaa-11e8-8526-81255faf64fb.png)

Thanks!

**Comment by ChrisLawford** [comment]
Are you asking why are the colours different because you have set them to be the same?

From what I can see it looks like you have selected the light blue colour for your resource.
```
<ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.LightBlue.xaml" />
<ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.LightBlue.xaml" />
```
This will set the PrimaryHueMidBrush to <Color x:Key="Primary500">#03a9f4</Color> as this is the colour set in [materialdesigncolours](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.LightBlue.Primary.xaml) the SecondaryAccentBrush will be set to <Color x:Key="Accent700">#0091ea</Color> again as can be found in [MaterialDesignColors](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.LightBlue.Accent.xaml)
As you can see the colour values are different so it makes complete sense that your image above shows the buttons with different colour backgrounds.

If this isn't what you are querying please do let me know.

**Comment by MichelMichels** [comment]
Closed due to inactivity
