### ISSUE TITLE
Dialog is not bounded by parent

### ISSUE THREAD

**Issue by cmeeren** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#997]
Using the MaterialDesignDemo project and changing the text of one of the dialogs to be much longer, the dialog overflows its parent. I'd expect the dialog to be bounded by the parent (max width = parent width - dialog margin). Is this a bug? If not, how can this reliably be prevented?

![image](https://user-images.githubusercontent.com/7766733/43552881-b8e07da4-95ec-11e8-9ce1-7e1df1460611.png)

**Comment by Keboo** [comment]
@cmeeren being able to have the dialog exceed the size of the window is actually by design. 
However to restrict it, there are a couple of options.
1. Set a MaxWidth binding on your dialog content. You may want to simply bind it to the ActualWidth of the parent Window. 
2. There is a PR that is scheduled to come in the next 2.5.0 release that will move the dialog from a popup, to be part of the visual tree of the window. This alternate style will force the dialog to be restricted because it will then be contained within the window. https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/760

**Comment by cmeeren** [comment]
Thanks. Unfortunately I couldn't get the MaxWidth to work with the DialogMargin property. I think I'll wait for the next release.

**Comment by Keboo** [comment]
@cmeeren the first 2.5.0 _prview_ [nuget package](https://www.nuget.org/packages/MaterialDesignThemes/2.5.0-ci1120) is up if you are interested in giving it a try. Would love to hear any feedback you have on it.

**Comment by cmeeren** [comment]
Thanks. Other things cropped up in my app and I am unable to test properly it while working on that. I'll get to it sooner or later (though no guarantees it'll be before 2.5.0 final).

**Comment by cmeeren** [comment]
I tried the preview now, but I get "an error occurred while finding the resource dictionary" on these two lines in my App.xaml (and my app throws on startup):

```xaml
<ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.Blue.xaml" />
<ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Lime.xaml" />
```
